---
title: "Untitled"
author: "Ruben Arslan"
date: "28 September 2017"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Helper
```{r helper}
source("0_helpers.R")
```


## Data
```{r}
### Import alldata used for birthorder and g-factors computed
alldata_birthorder = readRDS("data/alldata_birthorder.rds")

## For the imputation we want to clean the dataset and get rid of all uninteresting data
alldata_birthorder = alldata_birthorder %>%
  filter(!is.na(pidlink)) %>% # no individuals who are only known from the pregnancy file
  filter(is.na(lifebirths) | lifebirths == 2) %>% # remove 7 and 2 individuals who are known as stillbirth or miscarriage but still have PID
  select(-lifebirths) %>% 
  filter(!is.na(mother_pidlink)) %>% 
  select(-father_pidlink) %>% 
  filter(is.na(any_multiple_birth) | any_multiple_birth != 1) %>% # remove 7 and 2 individuals who are known as stillbirth or miscarriage but still have PID
  select(-starts_with("age_"), -wave, -any_multiple_birth, -multiple_birth) %>% 
  mutate(money_spent_smoking_log = if_else(is.na(money_spent_smoking_log) & ever_smoked == 0, 0, money_spent_smoking_log),
         amount = if_else(is.na(amount) & ever_smoked == 0, 0, amount),
         amount_still_smokers = if_else(is.na(amount_still_smokers) &  still_smoking == 0, 0, amount_still_smokers),
         birthyear = lubridate::year(birthdate))

## For the second imputation we only want to keep nice, non-problematic variables
alldata_birthorder = alldata_birthorder %>%
  select(-birthorder_uterus_alive, -birthorder_uterus_preg,
         -sibling_count_uterus_preg, -sibling_count_naive_ind, -sibling_count_uterus_alive,
         -words_immediate, -words_remembered_avg,
         -Total_score_highest,-Total_score_highest_type, -Math_score_highest,
         -Math_score_highest_type, -birthdate, -birthyear, -marriage_id,
         -money_spent_smoking_log,-amount_still_smokers, -total_worked, -total_missed, 
         -highest_education, -chron_order_birth, -alive, -death_yr, -death_month, -g_factor_early,
         -University_worked, -University_missed, - English_score_elementary,
         )

alldata_birthorder = alldata_birthorder %>%
  mutate(currently_attending_school = as.integer(currently_attending_school),
         attended_school = as.integer(attended_school),
         Type_of_test_elementary = as.integer(Type_of_test_elementary),
         Type_of_test_Junior_High = as.integer(Type_of_test_Junior_High),
         Type_of_test_Senior_High = as.integer(Type_of_test_Senior_High),
         random_si = as.integer(random_si)
         )

# recode Factor Variable as Dummy Variable
alldata_birthorder = left_join(alldata_birthorder,
                                alldata_birthorder %>%
                                  filter(!is.na(Category)) %>%
                                  mutate(var = 1) %>%
                                  select(pidlink, Category, var) %>%
                                  spread(Category, var, fill = 0, sep = "_"), by = "pidlink") %>%
  select(-Category)

# recode Factor Variable as Dummy Variable
alldata_birthorder = left_join(alldata_birthorder,
                                alldata_birthorder %>%
                                  filter(!is.na(Sector)) %>%
                                  mutate(var = 1) %>%
                                  select(pidlink, Sector, var) %>%
                                  spread(Sector, var, fill = 0, sep = "_"), by = "pidlink") %>%
  select(-Sector)





corr_pipe = . %>%  as.matrix() %>% 
Hmisc::rcorr(.) %>% {
  left_join(left_join(.$r %>% reshape2::melt() %>% rename(r = value), 
                      .$n %>% reshape2::melt() %>% rename(n = value), by = c("Var1", "Var2")),
            .$P %>% reshape2::melt() %>% rename(p = value), 
            by = c("Var1", "Var2"))
  } %>% 
  arrange(desc(r)) %>% 
  filter(Var1 != Var2)

attributes(alldata_birthorder$mother_pidlink)
zap_label <- function(x) {
  UseMethod("zap_label")
}
zap_label.data.frame <- function(x) {
  x[] <- lapply(x, zap_label)
  x
}
zap_label.default <- function(x) {
  attributes(x)$label <- NULL
  x
}
  
alldata_birthorder <- alldata_birthorder %>% haven::zap_labels() %>% haven::zap_formats() %>% zap_label()
str(alldata_birthorder)
alldata_birthorder %>% select_if(function(.)!is.numeric(.)) %>% names()

correlations = corr_pipe(alldata_birthorder %>% select_if(is.numeric))

alldata_birthorder <-  alldata_birthorder %>% select(`mother_pidlink`,  `age`, `male`, `birthorder_naive`, `sibling_count_naive`, `birthorder_genes`, `sibling_count_genes`,  
`raven_2015_young`, `math_2015_young`, `raven_2015_old`, `math_2015_old`, `words_delayed`, `adaptive_numbering`, `raven_2007_old`, `raven_2007_young`, `math_2007_young`, `math_2007_old`, `count_backwards`, 

`big5_ext`, `big5_con`, `big5_open`, `big5_neu`, `big5_agree`, `riskA`, `riskB`,

`Elementary_missed`, `Elementary_worked`, `attended_school`,

 # `currently_attending_school`,  `Type_of_test_elementary`, `Indonesia_score_elementary`, `English_score_elementary`, `Math_score_elemenatry`, `Total_score_elemenatry`, `Type_of_test_Junior_High`, `Indonesia_score_Junior_High`, `English_score_Junior_High`, `Math_score_Junior_High`, `Total_score_Junior_High`, `Type_of_test_Senior_High`, `Indonesia_score_Senior_High`, `English_score_Senior_High`, `Math_score_Senior_High`, `Total_score_Senior_High`, `Junior_high_worked`, `Senior_high_worked`, `University_worked`, `Junior_high_missed`, `Senior_high_missed`, `University_missed`,

`years_of_education`, `Self_employed`, `ever_smoked`, `still_smoking`, `wage_last_month_log`, `wage_last_year_log`,

`Category_Casual worker in agriculture`, `Category_Casual worker not in agriculture`, `Category_Government worker`, `Category_Private worker`, `Category_Self-employed`, `Category_Unpaid family worker`, 
`Sector_Agriculture, forestry, fishing and hunting`, `Sector_Construction`, `Sector_Electricity, gas, water`, `Sector_Finance, insurance, real estate and business services`, `Sector_Manufacturing`, `Sector_Mining and quarrying`, `Sector_Social services`, `Sector_Transportation, storage and communications`, `Sector_Wholesale, retail, restaurants and hotels`)
```

## R Markdown

```{r}
n_imputations.mitml = function(imps) {
  imps$iter$m
}
n_imputations.mids = function(imps) {
  imps$m
}
n_imputations.amelia = function(imps) {
  length(imps$imputations)
}
n_imputations = function(imps) { UseMethod("n_imputations") }

complete.mitml = mitml::mitmlComplete
complete.mids = mice::complete
complete = function(...) { UseMethod("complete") }

library(mice)
library(miceadds)
library(mitml)
library(lattice)
library(pan)

sort(round(miss_frac(alldata_birthorder),2))
# skimr::skim(alldata_birthorder)
```


# Small Dataset
```{r}
alldata_birthorder$miss_frac_person = rowMeans(is.na(alldata_birthorder))
qplot(alldata_birthorder$miss_frac_person)

alldatasm <-  alldata_birthorder %>% arrange(mother_pidlink) %>% slice(1:1000)
qplot(alldatasm$miss_frac_person)

alldata_birthorder$miss_frac_person <- NULL
alldatasm$miss_frac_person <- NULL

alldatasm$mother_pidlink = as.integer(alldatasm$mother_pidlink)

alldatasm = alldatasm %>% select(1:55)

alldatasm = alldatasm %>% select_if(is.integer)


imp4 = mice(alldatasm, blme_use = TRUE)
alldatasm[,55]

imp0 <- mice(alldatasm, maxit=0)
pred1 <- imp0$predictorMatrix
pred1
pred1 = quickpred(alldatasm, mincor = 0.1) #all variables that correlate > .01
pred1
pred1[pred1 == 1] = 2
meth1 <- imp0$method

# linear multilevel imputation using the function mice.impute.2l.norm()
# specify predictor_matrix using 1 = fixed effects, 2 = random effects, -2 = class variable, 0 = no effect
# we can set the mother_pidlink as class variable (= -2)
pred1[, "mother_pidlink"] = -2
# set imputation procedures
meth1[-1] <- "2l.pan"
meth1
pred1

imp1 <- mice(alldatasm, maxit=4, m=2, predictorMatrix=pred1, method=meth1)
imp2 <- mice(alldatasm, maxit=10, m = 2)


summary(lmer(raven_2015_old ~ (1 | mother_pidlink), alldatasm))
summary(lmer(raven_2015_old ~ (1 | mother_pidlink), complete(imp1,1)))
summary(lmer(raven_2015_old ~ (1 | mother_pidlink), complete(imp2,1)))
summary(lmer(big5_ext ~ (1 | mother_pidlink), alldatasm))
summary(lmer(big5_ext ~ (1 | mother_pidlink), complete(imp1,1)))
summary(lmer(big5_ext ~ (1 | mother_pidlink), complete(imp2,1)))

```



# Real Deal Dataset
```{r}
alldata_birthorder <- alldata_birthorder %>% select(-pidlink)
alldata_birthorder$mother_pidlink = as.integer(alldata_birthorder$mother_pidlink)
skimr::skim(alldata_birthorder)

imp0 <- mice(alldata_birthorder, maxit=0)

pred1 <- imp0$predictorMatrix
pred1
pred1 = quickpred(alldata_birthorder, mincor = 0.1) #all variables that correlate > .01
pred1
meth1 <- imp0$method

# linear multilevel imputation using the function mice.impute.2l.norm()
# specify predictor_matrix using 1 = fixed effects, 2 = random effects, -2 = class variable, 0 = no effect
# we can set the mother_pidlink as class variable (= -2)
pred1[, "mother_pidlink"] = -2
# set imputation procedures
meth1[-1] <- "2l.pan"
meth1
pred1

imp1 <- mice(alldata_birthorder, maxit = 4, m=2, predictorMatrix = pred1, method = meth1)

library(future)
plan(multicore(workers = 10))
imps = listenv::listenv()
for (i in seq_along(1:10)) {
  imps[[i]] %<-% mice(alldata_birthorder, m = 1, maxit = 15, predictorMatrix = pred1, method = meth1)
}
save(imps, file = "imps.rdata")

all_imps = as.list(imps)
save(all_imps, file = "imps2.rdata")
alldata_birthorder_i = all_imps[[1]]
for (i in seq_along(2:length(all_imps))) {
  alldata_birthorder_i = ibind(alldata_birthorder_i, all_imps[[i]])
}
saveRDS(alldata_birthorder_i, file = "alldata_birthorder_i_ml.rds")

summary(lmer(raven_2015_old ~ (1 | mother_pidlink), alldatasm))
summary(lmer(raven_2015_old ~ (1 | mother_pidlink), complete(imp1,1)))
summary(lmer(raven_2015_old ~ (1 | mother_pidlink), complete(imp2,1)))
summary(lmer(big5_ext ~ (1 | mother_pidlink), alldatasm))
summary(lmer(big5_ext ~ (1 | mother_pidlink), complete(imp1,1)))
summary(lmer(big5_ext ~ (1 | mother_pidlink), complete(imp2,1)))

```

```{r}
set.seed(123) # random seed so that other can replicate our imputation

# look at the dataset
colnames(alldata_birthorder)
head(alldata_birthorder)
dim(alldata_birthorder)
nrow(alldata_birthorder)
ncol(alldata_birthorder)
summary(alldata_birthorder)

alldata_birthorder = alldata_birthorder %>% mutate(const = 1)

#look at the missing data pattern
missingness_pattern = as.data.frame(md.pattern(alldata_birthorder))
length(missingness_pattern)

# look if multilevel is needed: Do you think it is necessary to take the multilevel structure into account? YES! There is a strong cluster structure going on. If we ignore the clustering in our imputation model, we may run into invalid inference. To stay as close to the true data model, we must take the cluster structure into account during imputation. ((https://gerkovink.github.io/miceVignettes/Multi_level/Multi_level_data.html))


alldata_birthorder$miss_frac_person = rowMeans(is.na(alldata_birthorder))
qplot(alldata_birthorder$miss_frac_person)

alldatasm <-  alldata_birthorder %>% arrange(miss_frac_person) %>% slice(1:1000)
qplot(alldatasm$miss_frac_person)

alldata_birthorder$miss_frac_person <- NULL
alldatasm$miss_frac_person <- NULL

predictor_matrix = quickpred(alldatasm, mincor = 0.01) #all variables that correlate > .01

# mother_pidlink is predicted by none of the other variables
table(predictor_matrix["mother_pidlink", ] == 0)
# mother_pidlink predicts 39 other variables
table(predictor_matrix[, "mother_pidlink"] == 0)




# mice.impute.2l.norm can not deal with fixed effects very well, thus we recode everything as a random effect (https://www.rdocumentation.org/packages/mice/versions/2.46.0/topics/mice.impute.2l.norm)
predictor_matrix[predictor_matrix == 1] = 2

# mice.impute.2l.norm can not deal with factor variables as class variables
alldatasm = alldatasm %>% mutate(mother_pidlink = as.integer(mother_pidlink))

method = vector(mode = "character", length = 61)
method[1] = "" # not necessary to predict motherpidlink
method[2:60] = "2l.pan" # we have to specify which variables shoul be predicted by multilevel modelling
method[61] = "" # not necessary to predict the constant

ini = mice(alldatasm, meth = method, maxit = 1, pred = predictor_matrix, seed = 71152)

alldatasm_i = mice(alldatasm, m = 5, maxit = 10, predictorMatrix = predictor_matrix)

plot(ini, c("riskB", "raven_2015_young", "birthorder_genes", "English_score_Junior_High", "years_of_education", "still_smoking"))
```



test
```{r}
alldata_birthorder$miss_frac_person = rowMeans(is.na(alldata_birthorder))
qplot(alldata_birthorder$miss_frac_person)
alldatasm <-  alldata_birthorder %>% arrange(miss_frac_person) %>% slice(1:1000)
alldata_birthorder$miss_frac_person <- NULL
alldatasm$miss_frac_person <- NULL

predictor_matrix = quickpred(alldatasm, mincor = 0.01)
predictor_matrix[, "mother_pidlink"] = 0
predictor_matrix["mother_pidlink", ] = 0

alldatasm_i = mice(alldatasm, m = 5, maxit = 10, predictorMatrix = predictor_matrix)


plot(alldatasm_i, c("riskB", "raven_2015_young", "birthorder_genes", "English_score_Junior_High", "Sector", "years_of_education", "still_smoking"))

# check densities of imputed/real
densityplot(ini, ~ riskB)
densityplot(ini, ~ years_of_education)
densityplot(alldatasm_i, ~ birthorder_genes)
densityplot(alldatasm_i, ~ g_factor_2015)

summary(lm(count_backwards ~ raven_2015_young, alldatasm))
summary(lm(count_backwards ~ raven_2015_young, complete(alldatasm_i,1)))
summary(lm(count_backwards ~ raven_2015_old, alldatasm))
summary(lm(count_backwards ~ raven_2015_old, complete(alldatasm_i,1)))
summary(lmer(count_backwards ~ (1 | mother_pidlink), alldatasm))
summary(lmer(count_backwards ~ (1 | mother_pidlink), complete(alldatasm_i,1)))
summary(lmer(riskA ~ (1 | mother_pidlink), alldatasm))
summary(lmer(riskA ~ (1 | mother_pidlink), complete(alldatasm_i,1)))

alldatasm_i <- mids2mitml.list(alldatasm_i)

alldatasm_i <- within(alldatasm_i, {
  g_factor_2015 <- rowMeans(scale(cbind(raven_2015_old, math_2015_old, count_backwards,  words_delayed, adaptive_numbering)))
})

alldatasm <- within(alldatasm, {
  g_factor_2015 <- rowMeans(scale(cbind(raven_2015_old, math_2015_old, count_backwards,  words_delayed, adaptive_numbering)))
})


qplot(alldatasm_i[[1]]$g_factor_2015)

alldatasm %>% {cor.test(.$g_factor_2015, .$years_of_education)}
alldatasm_i[[1]] %>% {cor.test(.$g_factor_2015, .$years_of_education)}
alldatasm %>% {cor.test(.$g_factor_2015, .$Math_score_Junior_High)}
alldatasm_i[[1]] %>% {cor.test(.$g_factor_2015, .$Math_score_Junior_High)}
```


```{r}
library(future)
plan(multicore(workers = 10))
predictor_matrix = quickpred(alldata_birthorder, mincor = 0.1)
# predictor_matrix[, "mother_pidlink"] = 0
# predictor_matrix["mother_pidlink", ] = 0


imps = listenv::listenv()
for (i in seq_along(1:10)) {
  imps[[i]] %<-% mice(alldata_birthorder, m = 1, maxit = 15, predictorMatrix = predictor_matrix)
}
save(imps, file = "imps.rdata")

all_imps = as.list(imps)
save(all_imps, file = "imps2.rdata")
alldata_birthorder_i = all_imps[[1]]
for (i in seq_along(2:length(all_imps))) {
  alldata_birthorder_i = ibind(alldata_birthorder_i, all_imps[[i]])
}
saveRDS(alldata_birthorder_i, file = "alldata_birthorder_i_ml.rds")

plot(alldata_birthorder_i, c("birthorder_uterus_alive", "birthorder_uterus_preg", "birthorder_genes",
"birthorder_naive"))

plot(alldata_birthorder_i, c("raven_2015_old", "math_2015_old", "count_backwards", "adaptive_numbering"))

plot(alldata_birthorder_i, c("words_immediate", "words_delayed", "words_remembered_avg"))

plot(alldata_birthorder_i, c("big5_ext", "big5_agree", "big5_con", "big5_open", "big5_neu"))



alldatasm_i <- mids2mitml.list(alldatasm_i)

alldatasm_i <- within(alldatasm_i, {
  g_factor_2015 <- rowMeans(scale(cbind(raven_2015_old, math_2015_old, count_backwards,  words_delayed, adaptive_numbering)))
})

alldatasm <- within(alldatasm, {
  g_factor_2015 <- rowMeans(scale(cbind(raven_2015_old, math_2015_old, count_backwards,  words_delayed, adaptive_numbering)))
})
plot(alldata_birthorder_i, c("birthorder_uterus_alive", "birthorder_uterus_preg", "birthorder_genes",
"birthorder_naive"))
                             

# check densities of imputed/real
densityplot(alldata_birthorder_i, ~ riskB)
densityplot(alldata_birthorder_i, ~ years_of_education)
densityplot(alldata_birthorder_i, ~ birthorder_genes)
densityplot(alldata_birthorder_i, ~ g_factor_2015)

summary(lm(count_backwards ~ raven_2015_young, complete(alldata_birthorder_i,1)))
summary(lm(count_backwards ~ raven_2015_old, alldata_birthorder))
summary(lm(count_backwards ~ raven_2015_old, complete(alldata_birthorder_i,1)))
summary(lmer(count_backwards ~ (1 | mother_pidlink), alldata_birthorder))
summary(lmer(count_backwards ~ (1 | mother_pidlink), complete(alldata_birthorder_i,1)))
summary(lmer(riskA ~ (1 | mother_pidlink), alldata_birthorder))
summary(lmer(riskA ~ (1 | mother_pidlink), complete(alldata_birthorder_i,1)))

alldata_birthorder_i <- mids2mitml.list(alldata_birthorder_i)

alldata_birthorder_i <- within(alldata_birthorder_i, {
  g_factor_2015 <- rowMeans(scale(cbind(raven_2015_old, math_2015_old, count_backwards,  words_delayed, adaptive_numbering)))
})

alldata_birthorder <- within(alldata_birthorder, {
  g_factor_2015 <- rowMeans(scale(cbind(raven_2015_old, math_2015_old, count_backwards,  words_delayed, adaptive_numbering)))
})


qplot(alldata_birthorder_i[[1]]$g_factor_2015)

alldata_birthorder %>% {cor.test(.$g_factor_2015, .$years_of_education)}
alldata_birthorder %>% {cor.test(.$g_factor_2015, .$Math_score_Junior_High)}
alldata_birthorder_i[[1]] %>% {cor.test(.$g_factor_2015, .$years_of_education)}
alldata_birthorder_i[[1]] %>% {cor.test(.$g_factor_2015, .$Math_score_Junior_High)}


saveRDS(alldata_birthorder_i, file="alldata_birthorder_i.rdata")
```

recompute g_factor
```{r}
within(alldata_birthorder_i, {
  g_factor_2015 <- rowMeans(scale(cbind(raven_2015_old, math_2015_old, count_backwards,  words_delayed, adaptive_numbering)))
})
```

analyse beispiel
```{r}
library(lme4)
fit <- with(alldata_birthorder_i, lmer(risk_taking ~ (menstruation_labelled + premenstrual_phase_fab + fertile_fab) * hormonal_contraception + (1 | short), subset = included_d == TRUE))
mitml::testEstimates(fit, var.comp = T)
fit[[1]] # fuer plots
```
