---
author: "Laura Botzet"
date: "10/26/2016"
output:
  html_document:
    lib_dir: library
    code_folding: "hide"
    self_contained: FALSE
---

# Preliminary Analyses {.tabset}

## Load libraries
```{r libraries}
library(lme4)
library(lmerTest)
library(ggplot2)
library(formr)
library(effects)
library(stringr)
library(forcats)
library(cowplot)
library(dplyr)
```

## helper
```{r helper}
apatheme=theme_bw()+
    theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.border=element_blank(),
        axis.line=element_line(),
        text=element_text(family='Times', size = 16))

 
plot_birthorder = function(model, ylabel, a, bo_var = "birthorder") {
  if(inherits(model, "merMod")) {
    varnames = names(model@frame)
  } else {
    varnames = names(model$model)
  }
  outcome = varnames[1]
  library(effects)
  library(tidyr)
  emm = allEffects(model)
  bo_var = names(emm)[names(emm) %contains% bo_var]
  cemm = as.data.frame(emm[[bo_var]]) %>%
    separate_(bo_var, into = c("Birth order", "Sibship"), sep = "/")
  number = spread(as.data.frame(table(model.frame(model)[`bo_var`])), Var1, Freq)
  n1 = paste0("1 (", sum(number$`1/1`), ")", seperate="")
  n2 = paste0("2 (", sum(number$`1/2`, number$`2/2`), ")", seperate="")
  n3 = paste0("3 (", sum(number$`1/3`, number$`2/3`, number$`3/3`), ")",
              seperate="")
  n4 = paste0("4 (", sum(number$`1/4`, number$`2/4`, number$`3/4`,
                                      number$`4/4`), ")", seperate="")
  n5 = paste0("5 (", sum(number$`1/5`, number$`2/5`, number$`3/5`,
                                      number$`4/5`, number$`5/5`), ")", seperate="")
  n5more = paste0("5+ (", sum(number$`1/5+`, number$`2/5+`, number$`3/5+`,
                                          number$`4/5+`, number$`5/5+`, number$`5+/5+`), ")",
                  seperate="")
  cemm = cemm %>%
    mutate(Sibship = recode_factor(Sibship, "1" = `n1`, "2" = `n2`, "3" = `n3`, "4" = `n4`,
                                   "5" = `n5`, "5+" = `n5more`))
  plotx = ggplot(cemm, aes(`Birth order`, y = fit, ymax = upper, ymin = lower,
                   colour = `Sibship`, group = `Sibship`)) + 
    geom_pointrange(stat = "identity", position = position_dodge(width = 0.5)) + 
    geom_line(position = position_dodge(width = 0.5)) +
    scale_y_continuous(name=ylabel, limits = c(-0.6, 0.5), breaks = c(-0.4, -0.2, 0,
                                                                  0.2, 0.4)) +
    labs(title=a) +
    apatheme +
    theme(legend.background = element_rect(fill="gray90", size=.5, linetype="dotted"),
          plot.title = element_text(hjust = 0)) +
    guides(colour=guide_legend(title = "Sibship"))
  print(plotx)
  assign(paste0("plot_", outcome, seperate=""),plotx,.GlobalEnv)
  
}

```


## Load data
```{r load data}
alldata_birthorder = readRDS("data/alldata_birthorder.rds")

```



## Data Preperations
```{r data preperations}
### Variables
alldata_birthorder = alldata_birthorder %>%
  mutate(
    # center birthyear
    birthyear = byear - mean(byear, na.rm = T),
    # Sex (1 = male, 2 = female)
    male = factor(sex.x == 1),
    male = ifelse(sex.x > 3, NA, male),
    # mother_pidlink has to be specified
    mother_pidlink = mother_pidlink.x,
    # center variables that are used for analysy - but first save old values
    old_g_factor = g_factor,
    old_raven = raven,
    old_math = math,
    old_count_backwards = count_backwards,
    old_words_remembered_avg = words_remembered_avg,
    old_words_immediate = words_immediate,
    old_words_delayed = words_delayed,
    old_adaptive_numbering = adaptive_numbering,
    old_big5_ext = big5_ext,
    old_big5_con = big5_con,
    old_big5_agree = big5_agree,
    old_big5_neu = big5_neu,
    old_big5_open = big5_open,
    old_riskA = riskA,
    old_riskB = riskB,
    g_factor = (g_factor - mean(g_factor, na.rm=T)) / sd(g_factor, na.rm=T),
    raven = (raven - mean(raven, na.rm=T)) / sd(raven, na.rm=T),
    math = (math - mean(math, na.rm=T)) / sd(math, na.rm=T),
    count_backwards = (count_backwards - mean(count_backwards, na.rm=T)) /
      sd(count_backwards, na.rm=T),
    words_remembered_avg = (words_remembered_avg - mean(words_remembered_avg, na.rm=T)) /
      sd(words_remembered_avg, na.rm=T),
    words_immediate = (words_immediate - mean(words_immediate, na.rm=T)) /
      sd(words_immediate, na.rm=T),
    words_delayed = (words_delayed - mean(words_delayed, na.rm=T)) /
      sd(words_delayed, na.rm=T),
    adaptive_numbering = (adaptive_numbering - mean(adaptive_numbering, na.rm=T)) /
      sd(adaptive_numbering, na.rm=T),
    big5_ext = (big5_ext - mean(big5_ext, na.rm=T)) / sd(big5_ext, na.rm=T),
    big5_con = (big5_con - mean(big5_con, na.rm=T)) / sd(big5_con, na.rm=T),
    big5_agree = (big5_agree - mean(big5_agree, na.rm=T)) / sd(big5_agree, na.rm=T),
    big5_open = (big5_open - mean(big5_open, na.rm=T)) / sd(big5_open, na.rm=T),
    big5_neu = (big5_neu - mean(big5_neu, na.rm=T)) / sd(big5_neu, na.rm=T),
    riskA = (riskA - mean(riskA, na.rm=T)) / sd(riskA, na.rm=T),
    riskB = (riskB - mean(riskB, na.rm=T)) / sd(riskB, na.rm=T)
        )
qplot(alldata_birthorder$g_factor)

### Birthorder and Sibling Count
alldata_birthorder = alldata_birthorder %>% 
  mutate(
# birthorder as factors with levels of 1, 2, 3, 4, 5, 5+
    birthorder_uterus_alive_factor = as.character(birthorder_uterus_alive),
    birthorder_uterus_alive_factor = ifelse(birthorder_uterus_alive > 5, "5+",
                                            birthorder_uterus_alive_factor),
    birthorder_uterus_alive_factor = factor(birthorder_uterus_alive_factor, 
                                            levels = c("1","2","3","4","5","5+")),
    sibling_count_uterus_alive_factor = as.character(sibling_count_uterus_alive),
    sibling_count_uterus_alive_factor = ifelse(sibling_count_uterus_alive > 5, "5+",
                                               sibling_count_uterus_alive_factor),
    sibling_count_uterus_alive_factor = factor(sibling_count_uterus_alive_factor, 
                                               levels = c("1","2","3","4","5","5+")),
    birthorder_uterus_preg_factor = as.character(birthorder_uterus_preg),
    birthorder_uterus_preg_factor = ifelse(birthorder_uterus_preg > 5, "5+",
                                           birthorder_uterus_preg_factor),
    birthorder_uterus_preg_factor = factor(birthorder_uterus_preg_factor,
                                           levels = c("1","2","3","4","5","5+")),
    sibling_count_uterus_preg_factor = as.character(sibling_count_uterus_preg),
    sibling_count_uterus_preg_factor = ifelse(sibling_count_uterus_preg > 5, "5+",
                                              sibling_count_uterus_preg_factor),
    sibling_count_uterus_preg_factor = factor(sibling_count_uterus_preg_factor, 
                                              levels = c("1","2","3","4","5","5+")),
    birthorder_genes_factor = as.character(birthorder_genes),
    birthorder_genes_factor = ifelse(birthorder_genes >5 , "5+", birthorder_genes_factor),
    birthorder_genes_factor = factor(birthorder_genes_factor, 
                                     levels = c("1","2","3","4","5","5+")),
    sibling_count_genes_factor = as.character(sibling_count_genes),
    sibling_count_genes_factor = ifelse(sibling_count_genes >5 , "5+",
                                        sibling_count_genes_factor),
    sibling_count_genes_factor = factor(sibling_count_genes_factor, 
                                        levels = c("1","2","3","4","5","5+")),
    # interaction birthorder * siblingcout for each birthorder
    count_birthorder_uterus_alive =
      factor(str_replace(as.character(interaction(birthorder_uterus_alive_factor,                                                              sibling_count_uterus_alive_factor)),
                        "\\.", "/"),
                                           levels =   c("1/1","1/2","2/2", "1/3",  "2/3",
                                                        "3/3", "1/4", "2/4", "3/4", "4/4",
                                                        "1/5", "2/5", "3/5", "4/5", "5/5",
                                                        "1/5+", "2/5+", "3/5+", "4/5+",
                                                        "5/5+", "5+/5+")),
    count_birthorder_uterus_preg =
      factor(str_replace(as.character(interaction(birthorder_uterus_preg_factor,                                                              sibling_count_uterus_preg_factor)), 
                         "\\.", "/"),
                                           levels =   c("1/1","1/2","2/2", "1/3",  "2/3",
                                                        "3/3", "1/4", "2/4", "3/4", "4/4",
                                                        "1/5", "2/5", "3/5", "4/5", "5/5",
                                                        "1/5+", "2/5+", "3/5+", "4/5+",
                                                        "5/5+", "5+/5+")),
    count_birthorder_genes =
      factor(str_replace(as.character(interaction(birthorder_genes_factor,                                                              sibling_count_genes_factor)), "\\.", "/"),
                                           levels =   c("1/1","1/2","2/2", "1/3",  "2/3",
                                                        "3/3", "1/4", "2/4", "3/4", "4/4",
                                                        "1/5", "2/5", "3/5", "4/5", "5/5",
                                                        "1/5+", "2/5+", "3/5+", "4/5+",
                                                        "5/5+", "5+/5+")))



```


## Between-family Analysis Intelligence

```{r Between-family Analysis Intelligence}
### Main Test: G-Factor - without covariats
## Main Test: G-Factor - uterus_alive
m_g_factor_uterus_alive = lm(g_factor ~ count_birthorder_uterus_alive,
                             data = alldata_birthorder)

anova(m_g_factor_uterus_alive)
plot_birthorder(m_g_factor_uterus_alive)

## Main Test: G-Factor - uterus_alive with covariats
m_g_factor_uterus_alive_covariats = lm(g_factor ~ birthorder_uterus_alive_factor  +
                             sibling_count_uterus_alive_factor 
                                       + birthyear + male,
                             data = alldata_birthorder)
anova(m_g_factor_uterus_alive_covariats)
m_g_factor_uterus_preg_covariats = lm(g_factor ~ birthorder_uterus_preg_factor  +
                             sibling_count_uterus_preg_factor 
                                       + birthyear + male,
                             data = alldata_birthorder)
anova(m_g_factor_uterus_alive_covariats)
m_g_factor_genes_covariats = lm(g_factor ~ birthorder_genes_factor  +
                             sibling_count_genes_factor 
                                       + birthyear + male,
                             data = alldata_birthorder)
anova(m_g_factor_genes_covariats)


m_g_factor_uterus_alive_covariats = lm(g_factor ~ count_birthorder_uterus_alive 
                                       + birthyear + male,
                             data = alldata_birthorder)
anova(m_g_factor_uterus_alive_covariats)
plot_birthorder(m_g_factor_uterus_alive_covariats)

## Main Test: G-Factor - uterus_preg
m_g_factor_uterus_preg = lm(g_factor ~ count_birthorder_uterus_preg,
                            data = alldata_birthorder)
summary(m_g_factor_uterus_preg)
plot_birthorder(m_g_factor_uterus_preg)

## Main Test: G-Factor - genes
m_g_factor_genes = lm(g_factor ~ count_birthorder_genes,
                            data = alldata_birthorder)
summary(m_g_factor_genes)
plot_birthorder(m_g_factor_genes)

## Main Test: G-Factor - genes with covariats
m_g_factor_genes_covariats = lm(g_factor ~ count_birthorder_genes
                                + birthyear + male,
                            data = alldata_birthorder)
summary(m_g_factor_genes_covariats)
plot_birthorder(m_g_factor_genes_covariats)

### Sub Tests
## Raven’s matrices test
# raven - uterus_alive
m_raven_uterus_alive = lm(raven ~ count_birthorder_uterus_alive,
                            data = alldata_birthorder)
summary(m_raven_uterus_alive)
plot_birthorder(m_raven_uterus_alive)

# raven - uterus_preg
m_raven_uterus_preg = lm(raven ~ count_birthorder_uterus_preg,
                            data = alldata_birthorder)
summary(m_raven_uterus_preg)
plot_birthorder(m_raven_uterus_preg)

# raven - genes
m_raven_genes = lm(raven ~ count_birthorder_genes,
                            data = alldata_birthorder)
summary(m_raven_genes)
plot_birthorder(m_raven_genes)

## Numeracy test
# math - uterus_alive
m_math_uterus_alive = lm(math ~ count_birthorder_uterus_alive,
                            data = alldata_birthorder)
summary(m_math_uterus_alive)
plot_birthorder(m_math_uterus_alive)

# math - uterus_preg
m_math_uterus_preg = lm(math ~ count_birthorder_uterus_preg,
                            data = alldata_birthorder)
summary(m_math_uterus_preg)
plot_birthorder(m_math_uterus_preg)

# math - genes
m_math_genes = lm(math ~ count_birthorder_genes,
                            data = alldata_birthorder)
summary(m_math_genes)
plot_birthorder(m_math_genes)

## Backwards counting
# count_backwards - uterus_alive
m_count_backwards_uterus_alive = lm(count_backwards ~ count_birthorder_uterus_alive,
                            data = alldata_birthorder)
summary(m_count_backwards_uterus_alive)
plot_birthorder(m_count_backwards_uterus_alive)

# count_backwards - uterus_preg
m_count_backwards_uterus_preg = lm(count_backwards ~ count_birthorder_uterus_preg,
                            data = alldata_birthorder)
summary(m_count_backwards_uterus_preg)
plot_birthorder(m_count_backwards_uterus_preg)

# count_backwards - genes
m_count_backwards_genes = lm(count_backwards ~ count_birthorder_genes,
                            data = alldata_birthorder)
summary(m_count_backwards_genes)
plot_birthorder(m_count_backwards_genes)

## Word Recall
# words_remembered_avg - uterus_alive
m_words_remembered_avg_uterus_alive = lm(words_remembered_avg ~
                                           count_birthorder_uterus_alive,
                            data = alldata_birthorder)
summary(m_words_remembered_avg_uterus_alive)
plot_birthorder(m_words_remembered_avg_uterus_alive)

# words_remembered_avg - uterus_preg
m_words_remembered_avg_uterus_preg = lm(words_remembered_avg ~
                                  count_birthorder_uterus_preg,
                            data = alldata_birthorder)
summary(m_words_remembered_avg_uterus_preg)
plot_birthorder(m_words_remembered_avg_uterus_preg)

# words_remembered_avg - genes
m_words_remembered_avg_genes = lm(words_remembered_avg ~ 
                               count_birthorder_genes,
                            data = alldata_birthorder)
summary(m_words_remembered_avg_genes)
plot_birthorder(m_words_remembered_avg_genes)

## Adaptive number series
# adaptive_numbering - uterus_alive
m_adaptive_numbering_uterus_alive = lm(adaptive_numbering ~
                                   count_birthorder_uterus_alive,
                            data = alldata_birthorder)
summary(m_adaptive_numbering_uterus_alive)
plot_birthorder(m_adaptive_numbering_uterus_alive)

# adaptive_numbering - uterus_preg
m_adaptive_numbering_uterus_preg = lm(adaptive_numbering ~
                                   count_birthorder_uterus_preg,
                            data = alldata_birthorder)
summary(m_adaptive_numbering_uterus_preg)
plot_birthorder(m_adaptive_numbering_uterus_preg)

# adaptive_numbering - genes
m_adaptive_numbering_genes = lm(adaptive_numbering ~ 
                              count_birthorder_genes,
                            data = alldata_birthorder)
summary(m_adaptive_numbering_genes)
plot_birthorder(m_adaptive_numbering_genes)

```


```{r Between-family Analysis Personality}
### Personality - without covariats
## Openness
# big5_open - uterus_alive
m_big5_open_uterus_alive = lm(big5_open ~ count_birthorder_uterus_alive,
                            data = alldata_birthorder)
summary(m_big5_open_uterus_alive)
plot_birthorder(m_big5_open_uterus_alive)

m_big5_open_uterus_alive_covariats = lm(big5_open ~ birthorder_uterus_alive_factor  +
                             sibling_count_uterus_alive_factor +
                                         birthyear + male,
                            data = alldata_birthorder)
anova(m_big5_open_uterus_alive_covariats)
plot_birthorder(m_big5_open_uterus_alive_covariats)

m_big5_open_uterus_alive_covariats = lm(big5_open ~ count_birthorder_uterus_alive +
                                         birthyear + male,
                            data = alldata_birthorder)
summary(m_big5_open_uterus_alive_covariats)
plot_birthorder(m_big5_open_uterus_alive_covariats)

# big5_open - uterus_preg
m_big5_open_uterus_preg = lm(big5_open ~ count_birthorder_uterus_preg,
                            data = alldata_birthorder)
summary(m_big5_open_uterus_preg)
plot_birthorder(m_big5_open_uterus_preg)

# big5_open - genes
m_big5_open_genes = lm(big5_open ~ count_birthorder_genes,
                            data = alldata_birthorder)
summary(m_big5_open_genes)
plot_birthorder(m_big5_open_genes)

## Extraversion
# big5_ext - uterus_alive
m_big5_ext_uterus_alive = lm(big5_ext ~ count_birthorder_uterus_alive ,
                            data = alldata_birthorder)
summary(m_big5_ext_uterus_alive)
plot_birthorder(m_big5_ext_uterus_alive)

m_big5_open_uterus_alive_covariats = lm(big5_open ~ birthorder_uterus_alive_factor  +
                             sibling_count_uterus_alive_factor +
                                         birthyear + male,
                            data = alldata_birthorder)
anova(m_big5_open_uterus_alive_covariats)
plot_birthorder(m_big5_open_uterus_alive_covariats)

m_big5_ext_uterus_alive_covariats = lm(big5_ext ~ count_birthorder_uterus_alive +
                                         birthyear + male,
                            data = alldata_birthorder)
summary(m_big5_ext_uterus_alive_covariats)
plot_birthorder(m_big5_ext_uterus_alive_covariats)

# big5_ext - uterus_preg
m_big5_ext_uterus_preg = lm(big5_ext ~ count_birthorder_uterus_preg,
                            data = alldata_birthorder)
summary(m_big5_ext_uterus_preg)
plot_birthorder(m_big5_ext_uterus_preg)

# big5_ext - genes
m_big5_ext_genes = lm(big5_ext ~ count_birthorder_genes,
                            data = alldata_birthorder)
summary(m_big5_ext_genes)
plot_birthorder(m_big5_ext_genes)

## Neuroticism
# big5_neu - uterus_alive
m_big5_neu_uterus_alive = lm(big5_neu ~ count_birthorder_uterus_alive,
                            data = alldata_birthorder)
summary(m_big5_neu_uterus_alive)
plot_birthorder(m_big5_neu_uterus_alive)

m_big5_neu_uterus_alive_covariats = lm(big5_neu ~ count_birthorder_uterus_alive +
                                         birthyear + male,
                            data = alldata_birthorder)
summary(m_big5_neu_uterus_alive_covariats)
plot_birthorder(m_big5_neu_uterus_alive_covariats)

# big5_neu - uterus_preg
m_big5_neu_uterus_preg = lm(big5_neu ~ count_birthorder_uterus_preg,
                            data = alldata_birthorder)
summary(m_big5_neu_uterus_preg)
plot_birthorder(m_big5_neu_uterus_preg)

# big5_neu - genes
m_big5_neu_genes = lm(big5_neu ~ count_birthorder_genes,
                            data = alldata_birthorder)
summary(m_big5_neu_genes)
plot_birthorder(m_big5_neu_genes)

## Aggreableness
# big5_agree - uterus_alive
m_big5_agree_uterus_alive = lm(big5_agree ~ count_birthorder_uterus_alive,
                            data = alldata_birthorder)
summary(m_big5_agree_uterus_alive)
plot_birthorder(m_big5_agree_uterus_alive)

m_big5_agree_uterus_alive_covariats = lm(big5_agree ~ count_birthorder_uterus_alive +
                                         birthyear + male,
                            data = alldata_birthorder)
summary(m_big5_agree_uterus_alive_covariats)
plot_birthorder(m_big5_agree_uterus_alive_covariats)


# big5_agree - uterus_preg
m_big5_agree_uterus_preg = lm(big5_agree ~ count_birthorder_uterus_preg,
                            data = alldata_birthorder)
summary(m_big5_agree_uterus_preg)
plot_birthorder(m_big5_agree_uterus_preg)

# big5_agree - genes
m_big5_agree_genes = lm(big5_agree ~ count_birthorder_genes,
                            data = alldata_birthorder)
summary(m_big5_agree_genes)
plot_birthorder(m_big5_agree_genes)

## Conscientiousness
# big5_con - uterus_alive
m_big5_con_uterus_alive = lm(big5_con ~ count_birthorder_uterus_alive,
                            data = alldata_birthorder)
summary(m_big5_con_uterus_alive)
plot_birthorder(m_big5_con_uterus_alive)

m_big5_con_uterus_alive_covariats = lm(big5_con ~ count_birthorder_uterus_alive +
                                         birthyear + male,
                            data = alldata_birthorder)
summary(m_big5_con_uterus_alive_covariats)
plot_birthorder(m_big5_con_uterus_alive_covariats)

# big5_con - uterus_preg
m_big5_con_uterus_preg = lm(big5_con ~ count_birthorder_uterus_preg,
                            data = alldata_birthorder)
summary(m_big5_con_uterus_preg)
plot_birthorder(m_big5_con_uterus_preg)

# big5_con - genes
m_big5_con_genes = lm(big5_con ~ count_birthorder_genes,
                            data = alldata_birthorder)
summary(m_big5_con_genes)
plot_birthorder(m_big5_con_genes)

```

## Risk
```{r Between-family Analysis Rsik Preference}
### Risk A
## Risk A - Uterus alive
m_riskA_uterus_alive = lm(riskA ~ count_birthorder_uterus_alive,
                            data = alldata_birthorder)
summary(m_riskA_uterus_alive)
plot_birthorder(m_riskA_uterus_alive)

m_riskA_uterus_alive_covariats = lm(riskA ~ count_birthorder_uterus_alive +
                                         birthyear + male,
                            data = alldata_birthorder)
summary(m_riskA_uterus_alive_covariats)
plot_birthorder(m_riskA_uterus_alive_covariats)


## Risk A - Uterus preg
m_riskA_uterus_preg = lm(riskA ~ count_birthorder_uterus_preg,
                            data = alldata_birthorder)
summary(m_riskA_uterus_preg)
plot_birthorder(m_riskA_uterus_preg)

## Risk A - genes
m_riskA_genes = lm(riskA ~ count_birthorder_genes,
                            data = alldata_birthorder)
summary(m_riskA_genes)
plot_birthorder(m_riskA_genes)

### Risk B
## Risk B - Uterus alive
m_riskB_uterus_alive = lm(riskB ~ count_birthorder_uterus_alive,
                            data = alldata_birthorder)
summary(m_riskB_uterus_alive)
plot_birthorder(m_riskB_uterus_alive)

m_riskB_uterus_alive_covariats = lm(riskB ~ count_birthorder_uterus_alive +
                                         birthyear + male,
                            data = alldata_birthorder)
summary(m_riskB_uterus_alive_covariats)
plot_birthorder(m_riskB_uterus_alive_covariats)


## Risk B - Uterus preg
m_riskB_uterus_preg = lm(riskB ~ count_birthorder_uterus_preg,
                            data = alldata_birthorder)
summary(m_riskB_uterus_preg)
plot_birthorder(m_riskB_uterus_preg)

## Risk B - genes
m_riskB_genes = lm(riskB ~ count_birthorder_genes,
                            data = alldata_birthorder)
summary(m_riskB_genes)
plot_birthorder(m_riskB_genes)
```




## Between Family data
```{r between family data}
check = alldata_birthorder %>% filter(!is.na(g_factor), !is.na(sibling_count_genes))
m_g_factor_uterus_alive_no = lm(g_factor ~ birthorder_uterus_alive_factor  +
                             sibling_count_uterus_alive_factor,
                             data = alldata_birthorder)
summary(m_g_factor_uterus_alive_no)

m_g_factor_uterus_preg_no = lm(g_factor ~ birthorder_uterus_preg_factor  +
                             sibling_count_uterus_preg_factor,
                             data = alldata_birthorder)
anova(m_g_factor_uterus_preg_no)

m_g_factor_genes_no = lm(g_factor ~ birthorder_genes_factor  +
                             sibling_count_genes_factor,
                             data = alldata_birthorder)
anova(m_g_factor_genes_no)

m_g_factor_uterus_alive = lm(g_factor ~ birthorder_uterus_alive_factor  +
                             sibling_count_uterus_alive_factor  + birthyear + male,
                             data = alldata_birthorder)
anova(m_g_factor_uterus_alive)
summary(m_g_factor_uterus_alive)
plot(allEffects(m_g_factor_uterus_alive))

m_g_factor_uterus_preg = lm(g_factor ~ birthorder_uterus_preg_factor  +
                             sibling_count_uterus_preg_factor  + birthyear + male,
                             data = alldata_birthorder)
anova(m_g_factor_uterus_preg)
summary(m_g_factor_uterus_preg)

m_g_factor_genes = lm(g_factor ~ birthorder_genes_factor  +
                             sibling_count_genes_factor  + birthyear + male,
                             data = alldata_birthorder)
anova(m_g_factor_genes)
summary(m_g_factor_genes)

check = alldata_birthorder %>% filter(!is.na(big5_ext), !is.na(sibling_count_genes))
m_big5_ext_uterus_alive_no = lm(big5_ext ~ birthorder_uterus_alive_factor  +
                             sibling_count_uterus_alive_factor,
                             data = alldata_birthorder)
summary(m_big5_ext_uterus_alive_no)
anova(m_big5_ext_uterus_alive_no)

m_big5_ext_uterus_preg_no = lm(big5_ext ~ birthorder_uterus_preg_factor  +
                             sibling_count_uterus_preg_factor,
                             data = alldata_birthorder)
summary(m_big5_ext_uterus_preg_no)
anova(m_big5_ext_uterus_preg_no)

m_big5_ext_genes_no = lm(big5_ext ~ birthorder_genes_factor  +
                             sibling_count_genes_factor,
                             data = alldata_birthorder)
summary(m_big5_ext_genes_no)
anova(m_big5_ext_genes_no)


m_big5_ext_uterus_alive = lm(big5_ext ~ birthorder_uterus_alive_factor  +
                             sibling_count_uterus_alive_factor  + birthyear + male,
                             data = alldata_birthorder)
anova(m_big5_ext_uterus_alive)
summary(m_big5_ext_uterus_alive)

plot(allEffects(m_big5_ext_uterus_alive))



m_big5_ext_uterus_preg = lm(big5_ext ~ birthorder_uterus_preg_factor  +
                             sibling_count_uterus_preg_factor  + birthyear + male,
                             data = alldata_birthorder)
anova(m_big5_ext_uterus_preg)
plot(allEffects(m_big5_ext_uterus_preg))

m_big5_ext_genes = lm(big5_ext ~ birthorder_genes_factor  +
                             sibling_count_genes_factor  + birthyear + male,
                             data = alldata_birthorder)
anova(m_big5_ext_genes)
plot(allEffects(m_big5_ext_genes))

m_big5_neu_uterus_alive_no = lm(big5_neu ~ birthorder_uterus_alive_factor  +
                             sibling_count_uterus_alive_factor,
                             data = alldata_birthorder)
anova(m_big5_neu_uterus_alive_no)
summary(m_big5_neu_uterus_alive_no)

m_big5_neu_uterus_preg_no = lm(big5_neu ~ birthorder_uterus_preg_factor  +
                             sibling_count_uterus_preg_factor,
                             data = alldata_birthorder)
anova(m_big5_neu_uterus_preg_no)
summary(m_big5_neu_uterus_preg_no)

m_big5_neu_genes_no = lm(big5_neu ~ birthorder_genes_factor  +
                             sibling_count_genes_factor,
                             data = alldata_birthorder)
anova(m_big5_neu_genes_no)
summary(m_big5_neu_genes_no)


m_big5_neu_uterus_alive = lm(big5_neu ~ birthorder_uterus_alive_factor  +
                             sibling_count_uterus_alive_factor + birthyear + male,
                             data = alldata_birthorder)
anova(m_big5_neu_uterus_alive)
summary(m_big5_neu_uterus_alive)
plot(allEffects(m_big5_neu_uterus_alive))

m_big5_neu_uterus_preg = lm(big5_neu ~ birthorder_uterus_preg_factor  +
                             sibling_count_uterus_preg_factor + birthyear + male,
                             data = alldata_birthorder)
anova(m_big5_neu_uterus_preg)
summary(m_big5_neu_uterus_preg)

m_big5_neu_genes = lm(big5_neu ~ birthorder_genes_factor  +
                             sibling_count_genes_factor + birthyear + male,
                             data = alldata_birthorder)
anova(m_big5_neu_genes)
summary(m_big5_neu_genes)

m_big5_con_uterus_alive_no = lm(big5_con ~ birthorder_uterus_alive_factor  +
                             sibling_count_uterus_alive_factor,
                             data = alldata_birthorder)
anova(m_big5_con_uterus_alive_no)
summary(m_big5_con_uterus_alive_no)

m_big5_con_uterus_preg_no = lm(big5_con ~ birthorder_uterus_preg_factor  +
                             sibling_count_uterus_preg_factor,
                             data = alldata_birthorder)
anova(m_big5_con_uterus_preg_no)
summary(m_big5_con_uterus_preg_no)

m_big5_con_genes_no = lm(big5_con ~ birthorder_genes_factor  +
                             sibling_count_genes_factor,
                             data = alldata_birthorder)
anova(m_big5_con_genes_no)
summary(m_big5_con_genes_no)

m_big5_con_uterus_alive = lm(big5_con ~ birthorder_uterus_alive_factor  +
                             sibling_count_uterus_alive_factor+ birthyear + male,
                             data = alldata_birthorder)
anova(m_big5_con_uterus_alive)
summary(m_big5_con_uterus_alive)
plot(allEffects(m_big5_con_uterus_alive))

m_big5_con_uterus_preg = lm(big5_con ~ birthorder_uterus_preg_factor  +
                             sibling_count_uterus_preg_factor+ birthyear + male,
                             data = alldata_birthorder)
anova(m_big5_con_uterus_preg)
summary(m_big5_con_uterus_preg)

m_big5_con_genes = lm(big5_con ~ birthorder_genes_factor  +
                             sibling_count_genes_factor+ birthyear + male,
                             data = alldata_birthorder)
anova(m_big5_con_genes)
summary(m_big5_con_genes)

m_big5_agree_uterus_alive_no = lm(big5_agree ~ birthorder_uterus_alive_factor  +
                             sibling_count_uterus_alive_factor,
                             data = alldata_birthorder)
anova(m_big5_agree_uterus_alive_no)
summary(m_big5_agree_uterus_alive_no)

m_big5_agree_uterus_preg_no = lm(big5_agree ~ birthorder_uterus_preg_factor  +
                             sibling_count_uterus_preg_factor,
                             data = alldata_birthorder)
anova(m_big5_agree_uterus_preg_no)
summary(m_big5_agree_uterus_preg_no)

m_big5_agree_genes_no = lm(big5_agree ~ birthorder_genes_factor  +
                             sibling_count_genes_factor,
                             data = alldata_birthorder)
anova(m_big5_agree_genes_no)
summary(m_big5_agree_genes_no)

m_big5_agree_uterus_alive = lm(big5_agree ~ birthorder_uterus_alive_factor  +
                             sibling_count_uterus_alive_factor + birthyear + male,
                             data = alldata_birthorder)
anova(m_big5_agree_uterus_alive)
plot(allEffects(m_big5_agree_uterus_alive))

m_big5_agree_uterus_preg = lm(big5_agree ~ birthorder_uterus_preg_factor  +
                             sibling_count_uterus_preg_factor + birthyear + male,
                             data = alldata_birthorder)
anova(m_big5_agree_uterus_preg)

m_big5_agree_genes = lm(big5_agree ~ birthorder_genes_factor  +
                             sibling_count_genes_factor + birthyear + male,
                             data = alldata_birthorder)
anova(m_big5_agree_genes)

m_big5_open_uterus_alive_no = lm(big5_open ~ birthorder_uterus_alive_factor  + 
                             sibling_count_uterus_alive_factor,
                             data = alldata_birthorder)
summary(m_big5_open_uterus_alive_no)

m_big5_open_uterus_preg_no = lm(big5_open ~ birthorder_uterus_preg_factor  + 
                             sibling_count_uterus_preg_factor,
                             data = alldata_birthorder)
anova(m_big5_open_uterus_preg_no)

m_big5_open_genes_no = lm(big5_open ~ birthorder_genes_factor  + 
                             sibling_count_genes_factor,
                             data = alldata_birthorder)
anova(m_big5_open_genes_no)

m_big5_open_uterus_alive = lm(big5_open ~ birthorder_uterus_alive_factor  + 
                             sibling_count_uterus_alive_factor + birthyear + male,
                             data = alldata_birthorder)
anova(m_big5_open_uterus_alive)
summary(m_big5_open_uterus_alive)
plot(allEffects(m_big5_open_uterus_alive))

m_big5_open_uterus_preg = lm(big5_open ~ birthorder_uterus_preg_factor  + 
                             sibling_count_uterus_preg_factor + birthyear + male,
                             data = alldata_birthorder)
anova(m_big5_open_uterus_preg)
summary(m_big5_open_uterus_preg)

m_big5_open_genes = lm(big5_open ~ birthorder_genes_factor  + 
                             sibling_count_genes_factor + birthyear + male,
                             data = alldata_birthorder)
anova(m_big5_open_genes)
summary(m_big5_open_genes)

check = alldata_birthorder %>% filter(!is.na(riskA), !is.na(sibling_count_genes))


m_riskA_uterus_alive_no = lm(riskA ~ birthorder_uterus_alive_factor  +
                             sibling_count_uterus_alive_factor,
                             data = alldata_birthorder)
anova(m_riskA_uterus_alive_no)

m_riskA_uterus_preg_no = lm(riskA ~ birthorder_uterus_preg_factor  +
                             sibling_count_uterus_preg_factor,
                             data = alldata_birthorder)
anova(m_riskA_uterus_preg_no)
summary(m_riskA_uterus_preg_no)
plot(allEffects(m_riskA_uterus_preg_no))

m_riskA_genes_no = lm(riskA ~ birthorder_genes_factor  +
                             sibling_count_genes_factor,
                             data = alldata_birthorder)
anova(m_riskA_genes_no)

m_riskA_uterus_alive = lm(riskA ~ birthorder_uterus_alive_factor  +
                             sibling_count_uterus_alive_factor  + birthyear + male,
                             data = alldata_birthorder)
anova(m_riskA_uterus_alive)
plot(allEffects(m_riskA_uterus_alive))

m_riskA_uterus_preg = lm(riskA ~ birthorder_uterus_preg_factor  +
                             sibling_count_uterus_preg_factor  + birthyear + male,
                             data = alldata_birthorder)
anova(m_riskA_uterus_preg)
summary(m_riskA_uterus_preg)
plot(allEffects(m_riskA_uterus_preg))

m_riskA_genes = lm(riskA ~ birthorder_genes_factor  +
                             sibling_count_genes_factor  + birthyear + male,
                             data = alldata_birthorder)
anova(m_riskA_genes)
summary(m_riskA_genes)
plot(allEffects(m_riskA_genes))

check = alldata_birthorder %>% filter(!is.na(riskB), !is.na(sibling_count_genes))
m_riskB_uterus_alive_no = lm(riskB ~ birthorder_uterus_alive_factor  + 
                             sibling_count_uterus_alive_factor,
                             data = alldata_birthorder)
anova(m_riskB_uterus_alive_no)

m_riskB_uterus_preg_no = lm(riskB ~ birthorder_uterus_preg_factor  + 
                             sibling_count_uterus_preg_factor,
                             data = alldata_birthorder)
anova(m_riskB_uterus_preg_no)

m_riskB_genes_no = lm(riskB ~ birthorder_genes_factor  + 
                             sibling_count_genes_factor,
                             data = alldata_birthorder)
anova(m_riskB_genes_no)

m_riskB_uterus_alive = lm(riskB ~ birthorder_uterus_alive_factor  + 
                             sibling_count_uterus_alive_factor + birthyear + male,
                             data = alldata_birthorder)
anova(m_riskB_uterus_alive)
plot(allEffects(m_riskB_uterus_alive))

m_riskB_uterus_preg = lm(riskB ~ birthorder_uterus_preg_factor  +
                             sibling_count_uterus_preg_factor  + birthyear + male,
                             data = alldata_birthorder)
anova(m_riskB_uterus_preg)
plot(allEffects(m_riskB_uterus_preg))

m_riskB_genes = lm(riskB ~ birthorder_genes_factor  +
                             sibling_count_genes_factor  + birthyear + male,
                             data = alldata_birthorder)
anova(m_riskB_genes)
plot(allEffects(m_riskB_genes))


  
```



## Intelligence - Within Family Analysis
```{r Intelligence - Within Family Analysis}
### Main Test: G-Factor
## Main Test: G-Factor - uterus_alive
# Without covariats
lme_g_factor_uterus_alive = lmer(g_factor ~ count_birthorder_uterus_alive +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_g_factor_uterus_alive)

plot_birthorder(lme_g_factor_uterus_alive)
# With covariats
lme_g_factor_uterus_alive_covariats = lmer(g_factor ~ count_birthorder_uterus_alive +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_g_factor_uterus_alive_covariats)
plot_birthorder(lme_g_factor_uterus_alive_covariats)

## Main Test: G-Factor - uterus_preg
# Without covariats
lme_g_factor_uterus_preg = lmer(g_factor ~ count_birthorder_uterus_preg +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_g_factor_uterus_preg)
plot_birthorder(lme_g_factor_uterus_preg)
# With covariats
lme_g_factor_uterus_preg_covariats = lmer(g_factor ~ count_birthorder_uterus_preg +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_g_factor_uterus_preg_covariats)
plot_birthorder(lme_g_factor_uterus_preg_covariats)

## Main Test: G-Factor - genes
# Without covariats
lme_g_factor_genes = lmer(g_factor ~ count_birthorder_genes +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_g_factor_genes)
plot_birthorder(lme_g_factor_genes)
# With covariats
lme_g_factor_genes_covariats = lmer(g_factor ~ count_birthorder_genes +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_g_factor_genes_covariats)
plot_birthorder(lme_g_factor_genes_covariats)
anova(lme_g_factor_genes_covariats)

### Raven
## Raven - uterus_alive
# Without covariats
lme_raven_uterus_alive = lmer(raven ~ count_birthorder_uterus_alive +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_raven_uterus_alive)
plot_birthorder(lme_raven_uterus_alive)
# With covariats
lme_raven_uterus_alive_covariats = lmer(raven ~ count_birthorder_uterus_alive +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_raven_uterus_alive_covariats)
plot_birthorder(lme_raven_uterus_alive_covariats)

## Raven - uterus_preg
# Without covariats
lme_raven_uterus_preg = lmer(raven ~ count_birthorder_uterus_preg +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_raven_uterus_preg)
plot_birthorder(lme_raven_uterus_preg)
# With covariats
lme_raven_uterus_preg_covariats = lmer(raven ~ count_birthorder_uterus_preg +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_raven_uterus_preg_covariats)
plot_birthorder(lme_raven_uterus_preg_covariats)

## Raven - genes
# Without covariats
lme_raven_genes = lmer(raven ~ count_birthorder_genes +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_raven_genes)
plot_birthorder(lme_raven_genes)
# With covariats
lme_raven_genes_covariats = lmer(raven ~ count_birthorder_genes +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_raven_genes_covariats)
plot_birthorder(lme_raven_genes_covariats)

### math
## math - uterus_alive
# Without covariats
lme_math_uterus_alive = lmer(math ~ count_birthorder_uterus_alive +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_math_uterus_alive)
plot_birthorder(lme_math_uterus_alive)
# With covariats
lme_math_uterus_alive_covariats = lmer(math ~ count_birthorder_uterus_alive +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_math_uterus_alive_covariats)
plot_birthorder(lme_math_uterus_alive_covariats)

## math - uterus_preg
# Without covariats
lme_math_uterus_preg = lmer(math ~ count_birthorder_uterus_preg +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_math_uterus_preg)
plot_birthorder(lme_math_uterus_preg)
# With covariats
lme_math_uterus_preg_covariats = lmer(math ~ count_birthorder_uterus_preg +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_math_uterus_preg_covariats)
plot_birthorder(lme_math_uterus_preg_covariats)

## math - genes
# Without covariats
lme_math_genes = lmer(math ~ count_birthorder_genes +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_math_genes)
plot_birthorder(lme_math_genes)
# With covariats
lme_math_genes_covariats = lmer(math ~ count_birthorder_genes +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_math_genes_covariats)
plot_birthorder(lme_math_genes_covariats)


### count_backwards
## count_backwards - uterus_alive
# Without covariats
lme_count_backwards_uterus_alive = lmer(count_backwards ~ count_birthorder_uterus_alive +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_count_backwards_uterus_alive)
plot_birthorder(lme_count_backwards_uterus_alive)
# With covariats
lme_count_backwards_uterus_alive_covariats = lmer(count_backwards ~
                                                    count_birthorder_uterus_alive +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_count_backwards_uterus_alive_covariats)
plot_birthorder(lme_count_backwards_uterus_alive_covariats)

## count_backwards - uterus_preg
# Without covariats
lme_count_backwards_uterus_preg = lmer(count_backwards ~ count_birthorder_uterus_preg +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_count_backwards_uterus_preg)
plot_birthorder(lme_count_backwards_uterus_preg)
# With covariats
lme_count_backwards_uterus_preg_covariats = lmer(count_backwards ~
                                                   count_birthorder_uterus_preg +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_count_backwards_uterus_preg_covariats)
plot_birthorder(lme_count_backwards_uterus_preg_covariats)

## count_backwards - genes
# Without covariats
lme_count_backwards_genes = lmer(count_backwards ~ count_birthorder_genes +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_count_backwards_genes)
plot_birthorder(lme_count_backwards_genes)
# With covariats
lme_count_backwards_genes_covariats = lmer(count_backwards ~ count_birthorder_genes +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_count_backwards_genes_covariats)
plot_birthorder(lme_count_backwards_genes_covariats)


### words_remembered_avg
## words_remembered_avg - uterus_alive
# Without covariats
lme_words_remembered_avg_uterus_alive = lmer(words_remembered_avg ~
                                               count_birthorder_uterus_alive +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_words_remembered_avg_uterus_alive)
plot_birthorder(lme_words_remembered_avg_uterus_alive)
# With covariats
lme_words_remembered_avg_uterus_alive_covariats = lmer(words_remembered_avg ~
                                                    count_birthorder_uterus_alive +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_words_remembered_avg_uterus_alive_covariats)
plot_birthorder(lme_words_remembered_avg_uterus_alive_covariats)

## words_remembered_avg - uterus_preg
# Without covariats
lme_words_remembered_avg_uterus_preg = lmer(words_remembered_avg ~
                                              count_birthorder_uterus_preg +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_words_remembered_avg_uterus_preg)
plot_birthorder(lme_words_remembered_avg_uterus_preg)
# With covariats
lme_words_remembered_avg_uterus_preg_covariats = lmer(words_remembered_avg ~
                                                   count_birthorder_uterus_preg +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_words_remembered_avg_uterus_preg_covariats)
plot_birthorder(lme_words_remembered_avg_uterus_preg_covariats)

## words_remembered_avg - genes
# Without covariats
lme_words_remembered_avg_genes = lmer(words_remembered_avg ~ count_birthorder_genes +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_words_remembered_avg_genes)
plot_birthorder(lme_words_remembered_avg_genes)
# With covariats
lme_words_remembered_avg_genes_covariats = lmer(words_remembered_avg ~
                                                  count_birthorder_genes +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_words_remembered_avg_genes_covariats)
plot_birthorder(lme_words_remembered_avg_genes_covariats)

### adaptive_numbering
## adaptive_numbering - uterus_alive
# Without covariats
lme_adaptive_numbering_uterus_alive = lmer(adaptive_numbering ~
                                             count_birthorder_uterus_alive +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_adaptive_numbering_uterus_alive)
plot_birthorder(lme_adaptive_numbering_uterus_alive)
# With covariats
lme_adaptive_numbering_uterus_alive_covariats = lmer(adaptive_numbering ~
                                                       count_birthorder_uterus_alive +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_adaptive_numbering_uterus_alive_covariats)
plot_birthorder(lme_adaptive_numbering_uterus_alive_covariats)

## adaptive_numbering - uterus_preg
# Without covariats
lme_adaptive_numbering_uterus_preg = lmer(adaptive_numbering ~
                                            count_birthorder_uterus_preg +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_adaptive_numbering_uterus_preg)
plot_birthorder(lme_adaptive_numbering_uterus_preg)
# With covariats
lme_adaptive_numbering_uterus_preg_covariats = lmer(adaptive_numbering ~
                                                      count_birthorder_uterus_preg +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_adaptive_numbering_uterus_preg_covariats)
plot_birthorder(lme_adaptive_numbering_uterus_preg_covariats)

## adaptive_numbering - genes
# Without covariats
lme_adaptive_numbering_genes = lmer(adaptive_numbering ~ count_birthorder_genes +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_adaptive_numbering_genes)
plot_birthorder(lme_adaptive_numbering_genes)
# With covariats
lme_adaptive_numbering_genes_covariats = lmer(adaptive_numbering ~ 
                                                count_birthorder_genes +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_adaptive_numbering_genes_covariats)
plot_birthorder(lme_adaptive_numbering_genes_covariats)

```

## Personality - Within Family Analysis
```{r Personality - Within Family Analysis}
### big5_open
## big5_open - uterus_alive
# Without covariats
lme_big5_open_uterus_alive = lmer(big5_open ~ count_birthorder_uterus_alive +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_big5_open_uterus_alive)
plot_birthorder(lme_big5_open_uterus_alive)
# With covariats
lme_big5_open_uterus_alive_covariats = lmer(big5_open ~ count_birthorder_uterus_alive +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_big5_open_uterus_alive_covariats)
plot_birthorder(lme_big5_open_uterus_alive_covariats)

## big5_open - uterus_preg
# Without covariats
lme_big5_open_uterus_preg = lmer(big5_open ~ count_birthorder_uterus_preg +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_big5_open_uterus_preg)
plot_birthorder(lme_big5_open_uterus_preg)
# With covariats
lme_big5_open_uterus_preg_covariats = lmer(big5_open ~ count_birthorder_uterus_preg +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_big5_open_uterus_preg_covariats)
plot_birthorder(lme_big5_open_uterus_preg_covariats)

## big5_open - genes
# Without covariats
lme_big5_open_genes = lmer(big5_open ~ count_birthorder_genes +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_big5_open_genes)
plot_birthorder(lme_big5_open_genes)
# With covariats
lme_big5_open_genes_covariats = lmer(big5_open ~ count_birthorder_genes +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_big5_open_genes_covariats)
plot_birthorder(lme_big5_open_genes_covariats)

### big5_ext
## big5_ext - uterus_alive
# Without covariats
lme_big5_ext_uterus_alive = lmer(big5_ext ~ count_birthorder_uterus_alive +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_big5_ext_uterus_alive)
plot_birthorder(lme_big5_ext_uterus_alive)
# With covariats
lme_big5_ext_uterus_alive_covariats = lmer(big5_ext ~ count_birthorder_uterus_alive +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_big5_ext_uterus_alive_covariats)
plot_birthorder(lme_big5_ext_uterus_alive_covariats)

## big5_ext - uterus_preg
# Without covariats
lme_big5_ext_uterus_preg = lmer(big5_ext ~ count_birthorder_uterus_preg +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_big5_ext_uterus_preg)
plot_birthorder(lme_big5_ext_uterus_preg)
# With covariats
lme_big5_ext_uterus_preg_covariats = lmer(big5_ext ~ count_birthorder_uterus_preg +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_big5_ext_uterus_preg_covariats)
plot_birthorder(lme_big5_ext_uterus_preg_covariats)

## big5_ext - genes
# Without covariats
lme_big5_ext_genes = lmer(big5_ext ~ count_birthorder_genes +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_big5_ext_genes)
plot_birthorder(lme_big5_ext_genes)
# With covariats
lme_big5_ext_genes_covariats = lmer(big5_ext ~ count_birthorder_genes +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_big5_ext_genes_covariats)
plot_birthorder(lme_big5_ext_genes_covariats)

### big5_neu
## big5_neu - uterus_alive
# Without covariats
lme_big5_neu_uterus_alive = lmer(big5_neu ~ count_birthorder_uterus_alive +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_big5_neu_uterus_alive)
plot_birthorder(lme_big5_neu_uterus_alive)
# With covariats
lme_big5_neu_uterus_alive_covariats = lmer(big5_neu ~ count_birthorder_uterus_alive +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_big5_neu_uterus_alive_covariats)
plot_birthorder(lme_big5_neu_uterus_alive_covariats)

## big5_neu - uterus_preg
# Without covariats
lme_big5_neu_uterus_preg = lmer(big5_neu ~ count_birthorder_uterus_preg +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_big5_neu_uterus_preg)
plot_birthorder(lme_big5_neu_uterus_preg)
# With covariats
lme_big5_neu_uterus_preg_covariats = lmer(big5_neu ~ count_birthorder_uterus_preg +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_big5_neu_uterus_preg_covariats)
plot_birthorder(lme_big5_neu_uterus_preg_covariats)

## big5_neu - genes
# Without covariats
lme_big5_neu_genes = lmer(big5_neu ~ count_birthorder_genes +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_big5_neu_genes)
plot_birthorder(lme_big5_neu_genes)
# With covariats
lme_big5_neu_genes_covariats = lmer(big5_neu ~ count_birthorder_genes +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_big5_neu_genes_covariats)
plot_birthorder(lme_big5_neu_genes_covariats)

### big5_agree
## big5_agree - uterus_alive
# Without covariats
lme_big5_agree_uterus_alive = lmer(big5_agree ~ count_birthorder_uterus_alive +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_big5_agree_uterus_alive)
plot_birthorder(lme_big5_agree_uterus_alive)
# With covariats
lme_big5_agree_uterus_alive_covariats = lmer(big5_agree ~ count_birthorder_uterus_alive +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_big5_agree_uterus_alive_covariats)
plot_birthorder(lme_big5_agree_uterus_alive_covariats)

## big5_agree - uterus_preg
# Without covariats
lme_big5_agree_uterus_preg = lmer(big5_agree ~ count_birthorder_uterus_preg +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_big5_agree_uterus_preg)
plot_birthorder(lme_big5_agree_uterus_preg)
# With covariats
lme_big5_agree_uterus_preg_covariats = lmer(big5_agree ~ count_birthorder_uterus_preg +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_big5_agree_uterus_preg_covariats)
plot_birthorder(lme_big5_agree_uterus_preg_covariats)

## big5_agree - genes
# Without covariats
lme_big5_agree_genes = lmer(big5_agree ~ count_birthorder_genes +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_big5_agree_genes)
plot_birthorder(lme_big5_agree_genes)
# With covariats
lme_big5_agree_genes_covariats = lmer(big5_agree ~ count_birthorder_genes +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_big5_agree_genes_covariats)
plot_birthorder(lme_big5_agree_genes_covariats)


### big5_con
## big5_con - uterus_alive
# Without covariats
lme_big5_con_uterus_alive = lmer(big5_con ~ count_birthorder_uterus_alive +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_big5_con_uterus_alive)
plot_birthorder(lme_big5_con_uterus_alive)
# With covariats
lme_big5_con_uterus_alive_covariats = lmer(big5_con ~ count_birthorder_uterus_alive +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_big5_con_uterus_alive_covariats)
plot_birthorder(lme_big5_con_uterus_alive_covariats)

## big5_con - uterus_preg
# Without covariats
lme_big5_con_uterus_preg = lmer(big5_con ~ count_birthorder_uterus_preg +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_big5_con_uterus_preg)
plot_birthorder(lme_big5_con_uterus_preg)
# With covariats
lme_big5_con_uterus_preg_covariats = lmer(big5_con ~ count_birthorder_uterus_preg +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_big5_con_uterus_preg_covariats)
plot_birthorder(lme_big5_con_uterus_preg_covariats)

## big5_con - genes
# Without covariats
lme_big5_con_genes = lmer(big5_con ~ count_birthorder_genes +
                                   (1 | mother_pidlink), data = alldata_birthorder)
summary(lme_big5_con_genes)
plot_birthorder(lme_big5_con_genes)
# With covariats
lme_big5_con_genes_covariats = lmer(big5_con ~ count_birthorder_genes +
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder)
summary(lme_big5_con_genes_covariats)
plot_birthorder(lme_big5_con_genes_covariats)
```


## Within Family data
```{r within family data}
lme_g_factor_uterus_alive_no = lmer(g_factor ~ birthorder_uterus_alive_factor +
                                 sibling_count_uterus_alive_factor + 
                                             (1 | mother_pidlink),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_g_factor_uterus_alive_no, ddf = "kenw")
summary(lme_g_factor_uterus_alive_no, ddf = "kenw")

lme_g_factor_uterus_preg_no = lmer(g_factor ~ birthorder_uterus_preg_factor +
                                 sibling_count_uterus_preg_factor + 
                                             (1 | mother_pidlink),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_g_factor_uterus_preg_no, ddf = "kenw")

lme_g_factor_genes_no = lmer(g_factor ~ birthorder_genes_factor +
                                 sibling_count_genes_factor + 
                                             (1 | marriage_id),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_g_factor_genes_no, ddf = "kenw")


lme_g_factor_uterus_alive = lmer(g_factor ~ birthorder_uterus_alive_factor +
                                 sibling_count_uterus_alive_factor + 
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)

anova(lme_g_factor_uterus_alive, ddf="kenw")
summary(lme_g_factor_uterus_alive, ddf="kenw")

lme_g_factor_uterus_preg = lmer(g_factor ~ birthorder_uterus_preg_factor +
                                 sibling_count_uterus_preg_factor + 
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)

anova(lme_g_factor_uterus_preg, ddf="kenw")

lme_g_factor_genes = lmer(g_factor ~ birthorder_genes_factor +
                                 sibling_count_genes_factor + 
                                             (1 | marriage_id) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)

anova(lme_g_factor_genes, ddf="kenw")

lme_big5_ext_uterus_alive_no = lmer(big5_ext ~ birthorder_uterus_alive_factor +
                                 sibling_count_uterus_alive_factor + 
                                             (1 | mother_pidlink),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_ext_uterus_alive_no, ddf="kenw")
summary(lme_big5_ext_uterus_alive_no, ddf="kenw")

lme_big5_ext_uterus_preg_no = lmer(big5_ext ~ birthorder_uterus_preg_factor +
                                 sibling_count_uterus_preg_factor + 
                                             (1 | mother_pidlink),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_ext_uterus_preg_no, ddf="kenw")

lme_big5_ext_genes_no = lmer(big5_ext ~ birthorder_genes_factor +
                                 sibling_count_genes_factor + 
                                             (1 | marriage_id),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_ext_genes_no, ddf="kenw")


lme_big5_ext_uterus_alive = lmer(big5_ext ~ birthorder_uterus_alive_factor +
                                 sibling_count_uterus_alive_factor + 
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_ext_uterus_alive, ddf="kenw")
summary(lme_big5_ext_uterus_alive, ddf="kenw")

lme_big5_ext_uterus_preg = lmer(big5_ext ~ birthorder_uterus_preg_factor +
                                 sibling_count_uterus_preg_factor + 
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_ext_uterus_preg, ddf="kenw")

lme_big5_ext_genes = lmer(big5_ext ~ birthorder_genes_factor +
                                 sibling_count_genes_factor + 
                                             (1 | marriage_id) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_ext_genes, ddf="kenw")

lme_big5_neu_uterus_alive_no = lmer(big5_neu ~ birthorder_uterus_alive_factor +
                                 sibling_count_uterus_alive_factor + 
                                             (1 | mother_pidlink),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_neu_uterus_alive_no, dff = "kenw")

lme_big5_neu_uterus_preg_no = lmer(big5_neu ~ birthorder_uterus_preg_factor +
                                 sibling_count_uterus_preg_factor + 
                                             (1 | mother_pidlink),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_neu_uterus_preg_no, dff = "kenw")

lme_big5_neu_genes_no = lmer(big5_neu ~ birthorder_genes_factor +
                                 sibling_count_genes_factor + 
                                             (1 | marriage_id),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_neu_genes_no, dff = "kenw")

lme_big5_neu_uterus_alive = lmer(big5_neu ~ birthorder_uterus_alive_factor +
                                 sibling_count_uterus_alive_factor + 
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_neu_uterus_alive, dff = "kenw")

lme_big5_neu_uterus_preg = lmer(big5_neu ~ birthorder_uterus_preg_factor +
                                 sibling_count_uterus_preg_factor + 
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_neu_uterus_preg, dff = "kenw")

lme_big5_neu_genes = lmer(big5_neu ~ birthorder_genes_factor +
                                 sibling_count_genes_factor + 
                                             (1 | marriage_id) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_neu_genes, dff = "kenw")


lme_big5_con_uterus_alive_no = lmer(big5_con ~ birthorder_uterus_alive_factor +
                                 sibling_count_uterus_alive_factor + 
                                             (1 | mother_pidlink),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_con_uterus_alive_no, ddf = "kenw")
summary(lme_big5_con_uterus_alive_no, ddf = "kenw")

lme_big5_con_uterus_preg_no = lmer(big5_con ~ birthorder_uterus_preg_factor +
                                 sibling_count_uterus_preg_factor + 
                                             (1 | mother_pidlink),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_con_uterus_preg_no, ddf = "kenw")

lme_big5_con_genes_no = lmer(big5_con ~ birthorder_genes_factor +
                                 sibling_count_genes_factor + 
                                             (1 | marriage_id),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_con_genes_no, ddf = "kenw")



lme_big5_con_uterus_alive = lmer(big5_con ~ birthorder_uterus_alive_factor +
                                 sibling_count_uterus_alive_factor + 
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_con_uterus_alive, ddf ="kenw")
plot(allEffects(lme_big5_con_uterus_alive))

lme_big5_con_uterus_preg = lmer(big5_con ~ birthorder_uterus_preg_factor +
                                 sibling_count_uterus_preg_factor + 
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_con_uterus_preg, ddf ="kenw")

lme_big5_con_genes = lmer(big5_con ~ birthorder_genes_factor +
                                 sibling_count_genes_factor + 
                                            (1 | marriage_id) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_con_genes, ddf ="kenw")

lme_big5_agree_uterus_alive_no = lmer(big5_agree ~ birthorder_uterus_alive_factor +
                                 sibling_count_uterus_alive_factor + 
                                             (1 | mother_pidlink),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_agree_uterus_alive_no, ddf = "kenw")

lme_big5_agree_uterus_preg_no = lmer(big5_agree ~ birthorder_uterus_preg_factor +
                                 sibling_count_uterus_preg_factor + 
                                             (1 | mother_pidlink),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_agree_uterus_preg_no, ddf = "kenw")

lme_big5_agree_genes_no = lmer(big5_agree ~ birthorder_genes_factor +
                                 sibling_count_genes_factor + 
                                             (1 | marriage_id),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_agree_genes_no, ddf = "kenw")

lme_big5_agree_uterus_alive = lmer(big5_agree ~ birthorder_uterus_alive_factor +
                                 sibling_count_uterus_alive_factor + 
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_agree_uterus_alive, ddf ="kenw")

lme_big5_agree_uterus_preg = lmer(big5_agree ~ birthorder_uterus_preg_factor +
                                 sibling_count_uterus_preg_factor + 
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_agree_uterus_preg, ddf ="kenw")

lme_big5_agree_genes = lmer(big5_agree ~ birthorder_genes_factor +
                                 sibling_count_genes_factor +
                                             (1 | marriage_id) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_agree_genes, ddf ="kenw")

lme_big5_open_uterus_alive_no = lmer(big5_open ~ birthorder_uterus_alive_factor +
                                 sibling_count_uterus_alive_factor + 
                                             (1 | mother_pidlink),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_open_uterus_alive_no, ddf= "kenw")
summary(lme_big5_open_uterus_alive_no, ddf= "kenw")

lme_big5_open_uterus_preg_no = lmer(big5_open ~ birthorder_uterus_preg_factor +
                                 sibling_count_uterus_preg_factor + 
                                             (1 | mother_pidlink),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_open_uterus_preg_no, ddf= "kenw")

lme_big5_open_genes_no = lmer(big5_open ~ birthorder_genes_factor +
                                 sibling_count_genes_factor + 
                                            (1 | marriage_id),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_open_genes_no, ddf= "kenw")

lme_big5_open_uterus_alive = lmer(big5_open ~ birthorder_uterus_alive_factor +
                                 sibling_count_uterus_alive_factor + 
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_open_uterus_alive, ddf = "kenw")
summary(lme_big5_open_uterus_alive, ddf = "kenw")

lme_big5_open_uterus_preg = lmer(big5_open ~ birthorder_uterus_preg_factor +
                                 sibling_count_uterus_preg_factor + 
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_open_uterus_preg, ddf = "kenw")

lme_big5_open_genes = lmer(big5_open ~ birthorder_genes_factor +
                                 sibling_count_genes_factor + 
                                             (1 | marriage_id) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_big5_open_genes, ddf = "kenw")

lme_riskA_uterus_alive_no = lmer(riskA ~ birthorder_uterus_alive_factor +
                                 sibling_count_uterus_alive_factor + 
                                             (1 | mother_pidlink),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_riskA_uterus_alive_no, ddf="kenw")

lme_riskA_uterus_preg_no = lmer(riskA ~ birthorder_uterus_preg_factor +
                                 sibling_count_uterus_preg_factor + 
                                             (1 | mother_pidlink),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_riskA_uterus_preg_no, ddf="kenw")

lme_riskA_genes_no = lmer(riskA ~ birthorder_genes_factor +
                                 sibling_count_genes_factor + 
                                             (1 | marriage_id),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_riskA_genes_no, ddf="kenw")

lme_riskA_uterus_alive = lmer(riskA ~ birthorder_uterus_alive_factor +
                                 sibling_count_uterus_alive_factor + 
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_riskA_uterus_alive, ddf="kenw")

lme_riskA_uterus_preg = lmer(riskA ~ birthorder_uterus_preg_factor +
                                 sibling_count_uterus_preg_factor + 
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_riskA_uterus_preg, ddf="kenw")
summary(lme_riskA_uterus_preg, ddf="kenw")

lme_riskA_genes = lmer(riskA ~ birthorder_genes_factor +
                                 sibling_count_genes_factor + 
                                             (1 | marriage_id) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_riskA_genes, ddf="kenw")


lme_riskB_uterus_alive_no = lmer(riskB ~ birthorder_uterus_alive_factor +
                                 sibling_count_uterus_alive_factor + 
                                             (1 | mother_pidlink),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_riskB_uterus_alive_no, ddf="kenw")

lme_riskB_uterus_preg_no = lmer(riskB ~ birthorder_uterus_preg_factor +
                                 sibling_count_uterus_preg_factor + 
                                             (1 | mother_pidlink),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_riskB_uterus_preg_no, ddf="kenw")
summary(lme_riskB_uterus_preg_no, ddf="kenw")

lme_riskB_genes_no = lmer(riskB ~ birthorder_genes_factor +
                                 sibling_count_genes_factor + 
                                             (1 | mother_pidlink),
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_riskB_genes_no, ddf="kenw")

lme_riskB_uterus_alive = lmer(riskB ~ birthorder_uterus_alive_factor +
                                 sibling_count_uterus_alive_factor + 
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_riskB_uterus_alive, ddf="kenw" )

lme_riskB_uterus_preg = lmer(riskB ~ birthorder_uterus_preg_factor +
                                 sibling_count_uterus_preg_factor + 
                                             (1 | mother_pidlink) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_riskB_uterus_preg, ddf="kenw")

lme_riskB_genes = lmer(riskB ~ birthorder_genes_factor +
                                 sibling_count_genes_factor + 
                                             (1 | marriage_id) + birthyear + male,
                                           data = alldata_birthorder, REML = FALSE)
anova(lme_riskB_genes, ddf="kenw")


```


## plots
```{r plots}

### Between
## Intelligence
m_g_factor_uterus_alive = lm(g_factor ~ count_birthorder_uterus_alive + birthyear + male,
                             data = alldata_birthorder) %>% plot_birthorder("Intelligence", "a")

## Personality
#Extraversion
m_big5_ext_uterus_alive = lm(big5_ext ~ count_birthorder_uterus_alive + birthyear + male,
                             data = alldata_birthorder) %>% plot_birthorder("Extraversion", "b")

# Neuroticism
m_big5_neu_uterus_alive = lm(big5_neu ~ count_birthorder_uterus_alive + birthyear + male,
                             data = alldata_birthorder) %>% plot_birthorder("Neuroticism", "c")

#Conscientiuosness
m_big5_con_uterus_alive = lm(big5_con ~ count_birthorder_uterus_alive + birthyear + male,
                             data = alldata_birthorder) %>%
  plot_birthorder("Cosncientiousness", "d")

#Agreeableness
m_big5_agree_uterus_alive = lm(big5_agree ~ count_birthorder_uterus_alive + birthyear +
                                 male, data = alldata_birthorder) %>%
  plot_birthorder("Agreeableness", "e")

#Openness
m_big5_open_uterus_alive = lm(big5_open ~ count_birthorder_uterus_alive + birthyear + male,
                             data = alldata_birthorder) %>% 
  plot_birthorder("Openness", "f")

##Risk
#Risk A
m_riskA_uterus_alive = lm(riskA ~ count_birthorder_uterus_alive + birthyear + male,
                             data = alldata_birthorder) %>% plot_birthorder("Risk A", "g")


# Risk B
m_riskB_uterus_alive = lm(riskB ~ count_birthorder_uterus_alive + birthyear + male,
                             data = alldata_birthorder) %>% plot_birthorder("Risk B", "h")


library(grid)
library(gridExtra)
plots = grid.arrange(plot_g_factor, plot_big5_ext, plot_big5_neu, plot_big5_con, plot_big5_agree,
             plot_big5_open, plot_riskA, plot_riskB,
             ncol = 2)

### Within
## Intelligence
lm_g_factor_uterus_alive = lmer(g_factor ~ count_birthorder_uterus_alive +
                                             (1 | mother_pidlink) + birthyear + male,
                             data = alldata_birthorder) %>% plot_birthorder("Intelligence", "a")

## Personality
#Extraversion
lm_big5_ext_uterus_alive = lmer(big5_ext ~ count_birthorder_uterus_alive +
                                             (1 | mother_pidlink) + birthyear + male,
                             data = alldata_birthorder) %>% plot_birthorder("Extraversion", "b")

# Neuroticism
lm_big5_neu_uterus_alive = lmer(big5_neu ~ count_birthorder_uterus_alive +
                                             (1 | mother_pidlink)  + birthyear + male,
                             data = alldata_birthorder) %>% plot_birthorder("Neuroticism", "c")

#Conscientiuosness
lm_big5_con_uterus_alive = lmer(big5_con ~ count_birthorder_uterus_alive +
                                             (1 | mother_pidlink)  + birthyear + male,
                             data = alldata_birthorder) %>%
  plot_birthorder("Cosncientiousness", "d")

#Agreeableness
lm_big5_agree_uterus_alive = lmer(big5_agree ~ count_birthorder_uterus_alive +
                                             (1 | mother_pidlink)  + birthyear +
                                 male, data = alldata_birthorder) %>%
  plot_birthorder("Agreeableness", "e")

#Openness
lm_big5_open_uterus_alive = lmer(big5_open ~ count_birthorder_uterus_alive +
                                             (1 | mother_pidlink)  + birthyear + male,
                             data = alldata_birthorder) %>% 
  plot_birthorder("Openness", "f")

##Risk
#Risk A
lm_riskA_uterus_alive = lmer(riskA ~ count_birthorder_uterus_alive +
                                             (1 | mother_pidlink)  + birthyear + male,
                             data = alldata_birthorder) %>% plot_birthorder("Risk A", "g")


# Risk B
lm_riskB_uterus_alive = lmer(riskB ~ count_birthorder_uterus_alive +
                                             (1 | mother_pidlink)  + birthyear + male,
                             data = alldata_birthorder) %>% plot_birthorder("Risk B", "h")


plots = grid.arrange(plot_g_factor, plot_big5_ext, plot_big5_neu, plot_big5_con, plot_big5_agree,
             plot_big5_open, plot_riskA, plot_riskB,
             ncol = 2)
```
