---
output: html_document
editor_options: 
  chunk_output_type: console
---
# <span style="color:#A6D854">Birth Order Effects</span> {.tabset}

## Helper
```{r helper}
source("0_helpers.R")
```


## Functions

```{r}

n_imputations.mitml = function(imps) {
  imps$iter$m
}
n_imputations.mids = function(imps) {
  imps$m
}
n_imputations.amelia = function(imps) {
  length(imps$imputations)
}
n_imputations = function(imps) { UseMethod("n_imputations") }

complete.mitml = mitml::mitmlComplete
complete.mids = mice::complete
complete = function(...) { UseMethod("complete") }

library(mice)
library(miceadds)
library(mitml)
```


## Load data
```{r Load Data}
birthorder = readRDS("data/alldata_birthorder_i.rds")
```

## Data preparations
```{r data preparations}
birthorder <- mids2mitml.list(birthorder)
birthorder <- within(birthorder, {
  g_factor_2015 <- rowMeans(scale(cbind(raven_2015_old, math_2015_old, count_backwards,  words_delayed, adaptive_numbering)))
})

birthorder = birthorder %>% tbl_df.mitml.list

### Birthorder and Sibling Count
birthorder = birthorder %>% 
  mutate(
# birthorder as factors with levels of 1, 2, 3, 4, 5, 5+
    birthorder_naive_factor = as.character(birthorder_naive),
    birthorder_naive_factor = ifelse(birthorder_naive > 5, "5+",
                                            birthorder_naive_factor),
    birthorder_naive_factor = factor(birthorder_naive_factor, 
                                            levels = c("1","2","3","4","5","5+")),
    sibling_count_naive_factor = as.character(sibling_count_naive),
    sibling_count_naive_factor = ifelse(sibling_count_naive > 5, "5+",
                                               sibling_count_naive_factor),
    sibling_count_naive_factor = factor(sibling_count_naive_factor, 
                                               levels = c("2","3","4","5","5+")),
    birthorder_genes_factor = as.character(birthorder_genes),
    birthorder_genes_factor = ifelse(birthorder_genes >5 , "5+", birthorder_genes_factor),
    birthorder_genes_factor = factor(birthorder_genes_factor, 
                                     levels = c("1","2","3","4","5","5+")),
    sibling_count_genes_factor = as.character(sibling_count_genes),
    sibling_count_genes_factor = ifelse(sibling_count_genes >5 , "5+",
                                        sibling_count_genes_factor),
    sibling_count_genes_factor = factor(sibling_count_genes_factor, 
                                        levels = c("2","3","4","5","5+")),
    # interaction birthorder * siblingcout for each birthorder
    count_birthorder_naive =
      factor(str_replace(as.character(interaction(birthorder_naive_factor,                                                              sibling_count_naive_factor)),
                        "\\.", "/"),
                                           levels =   c("1/2","2/2", "1/3",  "2/3",
                                                        "3/3", "1/4", "2/4", "3/4", "4/4",
                                                        "1/5", "2/5", "3/5", "4/5", "5/5",
                                                        "1/5+", "2/5+", "3/5+", "4/5+",
                                                        "5/5+", "5+/5+")),
    count_birthorder_genes =
      factor(str_replace(as.character(interaction(birthorder_genes_factor,                                                              sibling_count_genes_factor)), "\\.", "/"),
                                           levels =   c("1/2","2/2", "1/3",  "2/3",
                                                        "3/3", "1/4", "2/4", "3/4", "4/4",
                                                        "1/5", "2/5", "3/5", "4/5", "5/5",
                                                        "1/5+", "2/5+", "3/5+", "4/5+",
                                                        "5/5+", "5+/5+")))


# ### Variables
birthorder = birthorder %>%
  mutate(
    # center variables that are used for analysis
  raven_2015_old = scale(raven_2015_old),
  math_2015_old = scale(math_2015_old),
  count_backwards = scale(count_backwards),
  raven_2015_young = scale(raven_2015_young),
  math_2015_young = scale(math_2015_young),
  words_delayed = scale(words_delayed),
  adaptive_numbering = scale(adaptive_numbering),
  riskA = scale(riskA),
  riskB = scale(riskB),
  years_of_education_z = scale(years_of_education),
  wage_last_month_z = scale(wage_last_month_log),
  wage_last_year_z = scale(wage_last_year_log),
  big5_ext = scale(big5_ext),
  big5_con = scale(big5_con),
  big5_agree = scale(big5_agree),
  big5_open = scale(big5_open),
  big5_neu = scale(big5_neu)
)


```

## Intelligence {.active .tabset}
### g-factor {.tabset}

```{r}
# Specify your outcome
birthorder = birthorder %>% mutate(outcome = g_factor_2015)

## start with naive birthorder
birthorder <- birthorder %>%
                     mutate(sibling_count = sibling_count_naive,
                            birth_order_nonlinear = birthorder_naive_factor,
                            birth_order = birthorder_naive,
                            count_birth_order = count_birthorder_naive)
# naive covariates
model_naive_m1 <- with(birthorder, lmer(outcome ~ age + male + sibling_count + (1 | mother_pidlink)))
mitml::testEstimates(model_naive_m1, var.comp = T)

model_naive_m1_plot = lmer(outcome ~ age + male + sibling_count + (1 | mother_pidlink),
                   data = birthorder[[1]])
plot(allEffects(model_naive_m1_plot)) # fuer plots

# naive linear
model_naive_m2 <- with(birthorder, lmer(outcome ~ birth_order + age + male + sibling_count +
                                    (1 | mother_pidlink)))
mitml::testEstimates(model_naive_m2, var.comp = T)
model_naive_m2_plot = lmer(outcome ~ birth_order + age + male + sibling_count + (1 | mother_pidlink),
                   data = birthorder[[1]])
plot_birthorder(model_naive_m2_plot, separate = FALSE)

# naive factor
model_naive_m3 <- with(birthorder, lmer(outcome ~ birth_order_nonlinear + age + male +
                                          sibling_count + (1 | mother_pidlink)))
mitml::testEstimates(model_naive_m3, var.comp = T)
model_naive_m3_plot = lmer(outcome ~ birth_order_nonlinear + age + male + sibling_count +
                       (1 | mother_pidlink),
                   data = birthorder[[1]])
plot_birthorder(model_naive_m3_plot, separate = FALSE)

# naive interaction
model_naive_m4 <- with(birthorder, lmer(outcome ~ count_birth_order + age + male  +
                                    (1 | mother_pidlink)))
mitml::testEstimates(model_naive_m4, var.comp = T)
model_naive_m4_plot = lmer(outcome ~ count_birth_order + age + male +
                       (1 | mother_pidlink),
                   data = birthorder[[1]])
plot_birthorder(model_naive_m4_plot)

anova(model_naive_m1, model_naive_m2, model_naive_m3, model_naive_m4)

# genes birthorder
birthorder <- birthorder %>%
                     mutate(sibling_count = sibling_count_genes,
                            birth_order_nonlinear = birthorder_genes_factor,
                            birth_order = birthorder_genes,
                            count_birth_order = count_birthorder_genes)

# genes covariates
model_genes_m1 <- with(birthorder, lmer(outcome ~ age + male + sibling_count + (1 | mother_pidlink)))
mitml::testEstimates(model_genes_m1, var.comp = T)

model_genes_m1_plot = lmer(outcome ~ age + male + sibling_count + (1 | mother_pidlink),
                   data = birthorder[[1]])
plot(allEffects(model_genes_m1_plot)) # fuer plots

# genes linear
model_genes_m2 <- with(birthorder, lmer(outcome ~ birth_order + age + male + sibling_count +
                                    (1 | mother_pidlink)))
mitml::testEstimates(model_genes_m2, var.comp = T)
model_genes_m2_plot = lmer(outcome ~ birth_order + age + male + sibling_count + (1 | mother_pidlink),
                   data = birthorder[[1]])
plot_birthorder(model_genes_m2_plot, separate = FALSE)

# genes factor
model_genes_m3 <- with(birthorder, lmer(outcome ~ birth_order_nonlinear + age + male + sibling_count +
                                    (1 | mother_pidlink)))
mitml::testEstimates(model_genes_m3, var.comp = T)
model_genes_m3_plot = lmer(outcome ~ birth_order_nonlinear + age + male + sibling_count +
                       (1 | mother_pidlink),
                   data = birthorder[[1]])
plot_birthorder(model_genes_m3_plot, separate = FALSE)

# genes interaction
model_genes_m4 <- with(birthorder, lmer(outcome ~ count_birth_order + age + male  +
                                    (1 | mother_pidlink)))
mitml::testEstimates(model_genes_m4, var.comp = T)
model_genes_m4_plot = lmer(outcome ~ count_birth_order + age + male +
                       (1 | mother_pidlink),
                   data = birthorder[[1]])
plot_birthorder(model_genes_m4_plot)

anova(model_genes_m1, model_genes_m2, model_genes_m3, model_genes_m4)


library(coefplot)
multiplot(model_naive_m1, model_genes_m1)

```
