# Analyses {.tabset}

## Load libraries
```{r libraries}
library(lme4)
library(lmerTest)
library(ggplot2)
library(formr)
library(effects)
library(stringr)
library(forcats)
library(cowplot)
library(dplyr)
```

## helper
```{r helper}
source("0_helpers.R")
```


## Load data
```{r load data}
alldata_birthorder = readRDS("data/alldata_birthorder.rds")
```

## Data Preperations
```{r data preperations}
### Variables
alldata_birthorder = alldata_birthorder %>%
  mutate(
    # center birthyear
    birthyear = byear - mean(byear, na.rm = T),
    # Sex (1 = male, 2 = female)
    male = ifelse(sex.x == 1, 1L, 0L),
    male = ifelse(sex.x > 3, NA_integer_, male),
    male = factor(male),
    # mother_pidlink has to be specified
    mother_pidlink = mother_pidlink.x,
    # center variables that are used for analysy - but first save old values
    old_g_factor = g_factor,
    old_raven = raven,
    old_math = math,
    old_count_backwards = count_backwards,
    old_words_remembered_avg = words_remembered_avg,
    old_words_immediate = words_immediate,
    old_words_delayed = words_delayed,
    old_adaptive_numbering = adaptive_numbering,
    old_big5_ext = big5_ext,
    old_big5_con = big5_con,
    old_big5_agree = big5_agree,
    old_big5_neu = big5_neu,
    old_big5_open = big5_open,
    old_riskA = riskA,
    old_riskB = riskB,
    g_factor = (g_factor - mean(g_factor, na.rm=T)) / sd(g_factor, na.rm=T),
    raven = (raven - mean(raven, na.rm=T)) / sd(raven, na.rm=T),
    math = (math - mean(math, na.rm=T)) / sd(math, na.rm=T),
    count_backwards = (count_backwards - mean(count_backwards, na.rm=T)) /
      sd(count_backwards, na.rm=T),
    words_remembered_avg = (words_remembered_avg - mean(words_remembered_avg, na.rm=T)) /
      sd(words_remembered_avg, na.rm=T),
    words_immediate = (words_immediate - mean(words_immediate, na.rm=T)) /
      sd(words_immediate, na.rm=T),
    words_delayed = (words_delayed - mean(words_delayed, na.rm=T)) /
      sd(words_delayed, na.rm=T),
    adaptive_numbering = (adaptive_numbering - mean(adaptive_numbering, na.rm=T)) /
      sd(adaptive_numbering, na.rm=T),
    big5_ext = (big5_ext - mean(big5_ext, na.rm=T)) / sd(big5_ext, na.rm=T),
    big5_con = (big5_con - mean(big5_con, na.rm=T)) / sd(big5_con, na.rm=T),
    big5_agree = (big5_agree - mean(big5_agree, na.rm=T)) / sd(big5_agree, na.rm=T),
    big5_open = (big5_open - mean(big5_open, na.rm=T)) / sd(big5_open, na.rm=T),
    big5_neu = (big5_neu - mean(big5_neu, na.rm=T)) / sd(big5_neu, na.rm=T),
    riskA = (riskA - mean(riskA, na.rm=T)) / sd(riskA, na.rm=T),
    riskB = (riskB - mean(riskB, na.rm=T)) / sd(riskB, na.rm=T)
        )
qplot(alldata_birthorder$g_factor)

### Birthorder and Sibling Count
alldata_birthorder = alldata_birthorder %>% 
  mutate(
# birthorder as factors with levels of 1, 2, 3, 4, 5, 5+
    birthorder_uterus_alive_factor = as.character(birthorder_uterus_alive),
    birthorder_uterus_alive_factor = ifelse(birthorder_uterus_alive > 5, "5+",
                                            birthorder_uterus_alive_factor),
    birthorder_uterus_alive_factor = factor(birthorder_uterus_alive_factor, 
                                            levels = c("1","2","3","4","5","5+")),
    sibling_count_uterus_alive_factor = as.character(sibling_count_uterus_alive),
    sibling_count_uterus_alive_factor = ifelse(sibling_count_uterus_alive > 5, "5+",
                                               sibling_count_uterus_alive_factor),
    sibling_count_uterus_alive_factor = factor(sibling_count_uterus_alive_factor, 
                                               levels = c("1","2","3","4","5","5+")),
    birthorder_uterus_preg_factor = as.character(birthorder_uterus_preg),
    birthorder_uterus_preg_factor = ifelse(birthorder_uterus_preg > 5, "5+",
                                           birthorder_uterus_preg_factor),
    birthorder_uterus_preg_factor = factor(birthorder_uterus_preg_factor,
                                           levels = c("1","2","3","4","5","5+")),
    sibling_count_uterus_preg_factor = as.character(sibling_count_uterus_preg),
    sibling_count_uterus_preg_factor = ifelse(sibling_count_uterus_preg > 5, "5+",
                                              sibling_count_uterus_preg_factor),
    sibling_count_uterus_preg_factor = factor(sibling_count_uterus_preg_factor, 
                                              levels = c("1","2","3","4","5","5+")),
    birthorder_genes_factor = as.character(birthorder_genes),
    birthorder_genes_factor = ifelse(birthorder_genes >5 , "5+", birthorder_genes_factor),
    birthorder_genes_factor = factor(birthorder_genes_factor, 
                                     levels = c("1","2","3","4","5","5+")),
    sibling_count_genes_factor = as.character(sibling_count_genes),
    sibling_count_genes_factor = ifelse(sibling_count_genes >5 , "5+",
                                        sibling_count_genes_factor),
    sibling_count_genes_factor = factor(sibling_count_genes_factor, 
                                        levels = c("1","2","3","4","5","5+")),
    # interaction birthorder * siblingcout for each birthorder
    count_birthorder_uterus_alive =
      factor(str_replace(as.character(interaction(birthorder_uterus_alive_factor,                                                              sibling_count_uterus_alive_factor)),
                        "\\.", "/"),
                                           levels =   c("1/1","1/2","2/2", "1/3",  "2/3",
                                                        "3/3", "1/4", "2/4", "3/4", "4/4",
                                                        "1/5", "2/5", "3/5", "4/5", "5/5",
                                                        "1/5+", "2/5+", "3/5+", "4/5+",
                                                        "5/5+", "5+/5+")),
    count_birthorder_uterus_preg =
      factor(str_replace(as.character(interaction(birthorder_uterus_preg_factor,                                                              sibling_count_uterus_preg_factor)), 
                         "\\.", "/"),
                                           levels =   c("1/1","1/2","2/2", "1/3",  "2/3",
                                                        "3/3", "1/4", "2/4", "3/4", "4/4",
                                                        "1/5", "2/5", "3/5", "4/5", "5/5",
                                                        "1/5+", "2/5+", "3/5+", "4/5+",
                                                        "5/5+", "5+/5+")),
    count_birthorder_genes =
      factor(str_replace(as.character(interaction(birthorder_genes_factor,                                                              sibling_count_genes_factor)), "\\.", "/"),
                                           levels =   c("1/1","1/2","2/2", "1/3",  "2/3",
                                                        "3/3", "1/4", "2/4", "3/4", "4/4",
                                                        "1/5", "2/5", "3/5", "4/5", "5/5",
                                                        "1/5+", "2/5+", "3/5+", "4/5+",
                                                        "5/5+", "5+/5+")))



```


## G factor {.tabset}

### Maternal birth order {.tabset}

```{r}
g_factor_m1 = lmer(g_factor ~ birthyear + male + sibling_count + (1 | mother_pidlink),
                   data = alldata_birthorder %>%
                     rename(sibling_count = sibling_count_uterus_alive_factor,
                            birth_order_nonlinear = birthorder_uterus_alive_factor,
                            birth_order = birthorder_uterus_alive,
                            count_birth_order = count_birthorder_uterus_alive))
compare_models_markdown(g_factor_m1)
```

### Maternal pregnancy order {.tabset}

```{r}
g_factor_preg_m1 = lmer(g_factor ~ birthyear + male + sibling_count + (1 | mother_pidlink), data = alldata_birthorder %>% 
  rename(sibling_count = sibling_count_uterus_preg_factor,
         birth_order_nonlinear = birthorder_uterus_preg_factor,
         birth_order = birthorder_uterus_preg,
         count_birth_order = count_birthorder_uterus_preg
         ))
compare_models_markdown(g_factor_preg_m1)
```

### Parental Full Silbing Order {.tabset}

```{r}
g_factor_parental_m1 = lmer(g_factor ~ birthyear + male + sibling_count + (1 | marriage_id),
                            data = alldata_birthorder %>% 
  rename(sibling_count = sibling_count_genes_factor,
         birth_order_nonlinear = birthorder_genes_factor,
         birth_order = birthorder_genes,
         count_birth_order = count_birthorder_genes
         ))
compare_models_markdown(g_factor_parental_m1)
```
