---
  output: html_document
editor_options: 
  chunk_output_type: console
---

#### Parental full sibling order {.tabset .active}

##### Basic Model {.tabset}

###### Model Summary

```{r}
data_used = data_used %>%
  mutate(sibling_count = sibling_count_genes_factor,
         birth_order_nonlinear = birthorder_genes_factor,
         birth_order = birthorder_genes,
         count_birth_order = count_birthorder_genes)

data_used_plots = data_used[[1]]

model_genes_m1 <- with(data_used, lmer(outcome ~ poly(age, 3, raw = TRUE) + male + sibling_count + (1 | mother_pidlink), REML = FALSE))
x = mitml::testEstimates(model_genes_m1, var.comp = T)

y = as_tibble(x$estimates, rownames = "id")

y = y %>%
  mutate(CI_low = Estimate - 1.96 * Std.Error,
         CI_high = Estimate + 1.96 * Std.Error) %>%
  select(CI_low, CI_high)
CI_low = y$CI_low
CI_high = y$CI_high


x$estimates = cbind(x$estimates[,1:2], CI_low, CI_high, x$estimates[,3:7])
x
```

###### Coefficient Plot {.active}
```{r}
model_genes_m1_plot = lmer(outcome ~ poly(age, 3, raw = TRUE) + male + sibling_count + (1 | mother_pidlink),
                           data = data_used_plots, REML = FALSE)
plot(allEffects(model_genes_m1_plot))
```

##### Add Birth Order Linear {.tabset}

###### Model Summary
```{r}
model_genes_m2 <- with(data_used, lmer(outcome ~ birth_order + poly(age, 3, raw = TRUE) + male + sibling_count +
                                         (1 | mother_pidlink), REML = FALSE))
x = mitml::testEstimates(model_genes_m2, var.comp = T)

y = as_tibble(x$estimates, rownames = "id")

y = y %>%
  mutate(CI_low = Estimate - 1.96 * Std.Error,
         CI_high = Estimate + 1.96 * Std.Error) %>%
  select(CI_low, CI_high)
CI_low = y$CI_low
CI_high = y$CI_high


x$estimates = cbind(x$estimates[,1:2], CI_low, CI_high, x$estimates[,3:7])
x
```

###### Coefficient Plot  {.active}
```{r}
model_genes_m2_plot = lmer(outcome ~ birth_order + poly(age, 3, raw = TRUE) + male + sibling_count + (1 | mother_pidlink),
                           data = data_used_plots, REML = FALSE)
plot_birthorder2(model_genes_m2_plot, separate = FALSE)
```

##### Add Birth Order Factor {.tabset}

###### Model Summary
```{r}

model_genes_m3 <- with(data_used, lmer(outcome ~ birth_order_nonlinear + poly(age, 3, raw = TRUE) + male + sibling_count +
                                         (1 | mother_pidlink), REML = FALSE))
x = mitml::testEstimates(model_genes_m3, var.comp = T)

y = as_tibble(x$estimates, rownames = "id")

y = y %>%
  mutate(CI_low = Estimate - 1.96 * Std.Error,
         CI_high = Estimate + 1.96 * Std.Error) %>%
  select(CI_low, CI_high)
CI_low = y$CI_low
CI_high = y$CI_high


x$estimates = cbind(x$estimates[,1:2], CI_low, CI_high, x$estimates[,3:7])
x
```

###### Coefficient Plot {.active}
```{r}
model_genes_m3_plot = lmer(outcome ~ birth_order_nonlinear + poly(age, 3, raw = TRUE) + male + sibling_count +
                             (1 | mother_pidlink),
                           data = data_used_plots, REML = FALSE)
plot_birthorder(model_genes_m3_plot, separate = FALSE)
```

##### Add Interaction {.tabset .active}

###### Model Summary
```{r}
model_genes_m4 <- with(data_used, lmer(outcome ~ count_birth_order + poly(age, 3, raw = TRUE) + male  +
                                         (1 | mother_pidlink), REML = FALSE))
x = mitml::testEstimates(model_genes_m4, var.comp = T)

y = as_tibble(x$estimates, rownames = "id")

y = y %>%
  mutate(CI_low = Estimate - 1.96 * Std.Error,
         CI_high = Estimate + 1.96 * Std.Error) %>%
  select(CI_low, CI_high)
CI_low = y$CI_low
CI_high = y$CI_high


x$estimates = cbind(x$estimates[,1:2], CI_low, CI_high, x$estimates[,3:7])
x

```

###### Coefficient Plot {.active}
```{r}
model_genes_m4_plot = lmer(outcome ~ count_birth_order + poly(age, 3, raw = TRUE) + male +
                             (1 | mother_pidlink),
                           data = data_used_plots, REML = FALSE)
plot_birthorder(model_genes_m4_plot)
```

##### Model Comparison
```{r}
anova(model_genes_m1, model_genes_m2, model_genes_m3, model_genes_m4)

```
