---
output: html_document
editor_options: 
  chunk_output_type: console
---

##### Basic Model {.tabset}

###### Model Summary
```{r}
summary(m1_covariates_only)
```

###### Coefficient Plot
```{r}
plot(allEffects(m1_covariates_only))
```

##### Add Birth Order Linear {.tabset}

###### Model Summary
```{r}
m2_birthorder_linear = update(m1_covariates_only, formula = . ~ . + birth_order)
summary(m2_birthorder_linear)
```

###### Coefficient Plot
```{r}
plot_birthorder_nonz(m2_birthorder_linear, separate = FALSE)
```

##### Add Birth Order Factor {.tabset}

###### Model Summary
```{r}
m3_birthorder_nonlinear = update(m1_covariates_only, formula = . ~ . + birth_order_nonlinear)
summary(m3_birthorder_nonlinear)
```

###### Coefficient Plot
```{r}
plot_birthorder_nonz(m3_birthorder_nonlinear, separate = FALSE)
```

##### Add Interaction {.tabset}

###### Model Summary
```{r}
m4_interaction = update(m3_birthorder_nonlinear, formula = . ~ . - birth_order_nonlinear - sibling_count + count_birth_order)
summary(m4_interaction)
```

###### Coefficient Plot
```{r}
plot_birthorder_nonz(m4_interaction)
```

##### Model Comparison
```{r}
###### Model 1 - Model 2
anova(m1_covariates_only, m2_birthorder_linear, m3_birthorder_nonlinear, m4_interaction)
```

