---
title: "x_unused"
author: "Laura Botzet"
date: "14.11.2016"
output: html_document
---


## Determine parents that we can use for birthorder calcualations
```{r parents for birthorder}
### All women who completed book 4 (we have all informatios about their children)
mothers_15_57 = b4_cov %>% select(pidlink)

### All men and women >57 who completed book 3b (we have all informatios about their children)
fathers_restmothers = b3b_cov %>% select(pidlink, sex) # include sex to determin wether we are talking about a mother or a father; 1 = male, 3 = female

### All fathers that we have all informations that we need to compute birthorder for children
fathers_allinfo = fathers_restmothers %>%
  filter(sex==1)

### All mothers that we have all inforamtions that we need to compute birthorder for children
mothers_allinfo = fathers_restmothers %>%
  filter(sex==3)
mothers_allinfo = bind_rows(mothers_allinfo, mothers_15_57)
mothers_allinfo = mothers_allinfo %>% distinct(pidlink, .keep_all = TRUE) # completed either book 4 or book 3b or both
```



## Select informations about additional siblings from mother
```{r Select informations about additional sibilngs from mother}
# We have three sources for informations about the children of one women: Biological children (Book 4, women aged 15-57 & maried), Adopted Children (Book 4, women aged 15-57 & maried), All children (Book 3b, >57 or never maried)

## Get all the informations about biological children (Book 4, women aged 15-57 & maried)
motherinformations_bio = b4_ba6 %>% select(hhid14_9, pidlink, ba63cx, ba64, ba64bmt, ba64byr, ba65, ba65mt, ba65ayr, ba66)
#Rename variables:
motherinformations_bio = rename(motherinformations_bio, kind_of_child_m = ba63cx, sex_m = ba64,  birth_month_m = ba64bmt, birth_year_m = ba64byr, alive_m = ba65, death_month_m = ba65mt, death_year_m = ba65ayr, current_age_or_death_age_m = ba66, mother_pidlink = pidlink) 

## Get all the informations about non-biological children (Book 4, women aged 15-57 & maried)
motherinformations_adop = b4_bx6 %>% select(hhid14_9, pidlink, bx63cx, bx64, bx64bmt, bx64byr, bx65, bx65amt, bx65ayr, bx66)
#Rename variables:
motherinformations_adop = rename(motherinformations_adop, kind_of_child_m = bx63cx, sex_m = bx64,  birth_month_m = bx64bmt, birth_year_m = bx64byr, alive_m = bx65, death_month_m = bx65amt, death_year_m = bx65ayr, current_age_or_death_age_m = bx66, mother_pidlink = pidlink) 

## Get the rest informations (Book 3b, >57 or never maried)
motherinformations_old = subset(b3b_ba6, pidlink %in% mothers_allinfo$pidlink) # we only want female participants
motherinformations_old = motherinformations_old %>% select(hhid14_9, pidlink, ba63cx, ba64, ba64bmt, ba64byr, ba65, ba65amt, ba65ayr, ba66)
# Rename variables:
motherinformations_old = rename(motherinformations_old, kind_of_child_m = ba63cx, sex_m = ba64,  birth_month_m = ba64bmt, birth_year_m = ba64byr, alive_m = ba65, death_month_m = ba65amt, death_year_m = ba65ayr, current_age_or_death_age_m = ba66, mother_pidlink = pidlink) 

## Combine all informations
motherinformations = bind_rows(motherinformations_bio, motherinformations_adop)
motherinformations = bind_rows(motherinformations, motherinformations_old)

## Create variable that contains pidlink of mother and birthdate of child:
#Set all variables missing that have not been reported:
motherinformations$birth_month_m[ motherinformations$birth_month_m>12] = NA
motherinformations$birth_year_m[ motherinformations$birth_year_m>2016] = NA
motherinformations$birth_year_m[ motherinformations$birth_year_m<1930] = NA # get rid of some weird byears (1079, 98,80, 8)
motherinformations$birth_month_m[ is.nan(motherinformations$birth_month_m) ] = NA
motherinformations$birth_year_m[ is.nan(motherinformations$birth_year_m)] = NA
motherinformations$death_month_m[ motherinformations$death_month_m>12] = NA
motherinformations$death_year_m[ motherinformations$death_year_m>2016] = NA
motherinformations$death_month_m[ is.nan(motherinformations$death_month_m) ] = NA
motherinformations$death_year_m[ is.nan(motherinformations$death_year_m)] = NA

motherinformations = motherinformations %>%
    mutate(mother_birthdate = str_c(mother_pidlink, "-",
          all_available_info_birth_date(birth_year_m, birth_month_m))) # mother_pidlink-YYYY-MM; is NA if birth_year is missing

## Remove all with missing mothers/birth_years
motherinformations = motherinformations %>%
  filter(!is.na(mother_birthdate))

## Remove duplicats (some children are reported both in the biological and in the adopted list - confusing question?)
motherinformations = motherinformations %>% distinct(mother_birthdate, .keep_all = TRUE)


```



## Combine informations from mother and individuals file
```{r Combine informations from father, mother and individuals file}
### For our future analysis we only want informations about individuals whose mother reported informations about all other siblings (living in the same HH and not living in the same HH)
individuals_siblinginfos = individuals %>%
  filter(mother_reported_on_other_sibs == 1)

### Combination of individual data and motherinformations
individualsinformations_only = left_join(individuals_siblinginfos, motherinformations, by = "mother_birthdate")
motherinformations_only = anti_join(motherinformations, individuals_siblinginfos, by = "mother_birthdate") # all rows from motherinformations that do not occur in individuals
parentscheck = bind_rows(individualsinformations_only, motherinformations_only) # combines all rows in individual that occur in motherinformationsfile only

### All mother_pidlinks should be in one column:
parentscheck$mother_pidlink = ifelse(is.na(parentscheck$mother_pidlink), parentscheck$mother_pidlink.x, parentscheck$mother_pidlink)

### For the individuals that are only in the motherinformationsfile we do not have a pidlink - so we create one (counting from one to the end of all missing pidlinks is reached)
parentscheck$pidlink = ifelse(is.na(parentscheck$pidlink), c(1:sum(is.na(parentscheck$pidlink))), parentscheck$pidlink)
```


## Birth Orders

```{r Birth Orders}
## Create a variable that contains the birthdate for all individuals:
parentscheck = parentscheck %>%
    mutate(birth_ind = all_available_info_birth_date(ar08yr, ar08mth, ar08day), # from individuals file
           birth_parents = all_available_info_birth_date(birth_year_m, birth_month_m)) %>% # from parents file
    aggregate2sources("birth", "birth_ind", "birth_parents") # aggregate both informations in one column

#Remove missing birthdates:
parentscheck = parentscheck %>%
  filter(!is.na(birth))


### Preperations
## Biological Birthorder - Order in Uterus: We only want to include biological children: 
# Modify kind_of_child_variable_m (1 = bio_child, 2 = stepchild, 3 = adopted):
parentscheck$kind_of_child_m = ifelse(
  is.na(parentscheck$kind_of_child_m), 1, # those who don't have this var are from the individuals file and are biological kids
  parentscheck$kind_of_child_m) # the ones from the minfo file can be adopted, stepchildren, etc.

# Create Birth for biological children:
parentscheck = parentscheck %>%
  mutate(birth_bio = ifelse(kind_of_child_m == 1, birth, NA))

## Biological Birthorder - Genes
# Create birth variable for siblings that share the same mother and father
parentscheck = parentscheck %>%
  mutate(birth_genes = ifelse(!is.na(mother_father_dyad), birth, NA))


## Social Birthorder: Calculate Death Age:
# We have two sources for death informations: The household roster (Book K, Section ar,) and the mother informations (Book 4). We need to combine the informations that we have
parentscheck$alive_m = ifelse(is.na(parentscheck$alive_m), 1, parentscheck$alive_m) # 1=alive, 3=dead

# For the mother informations file some age information is missing. So we calculate it by substracting the birthyear/deathyear from the year of the interview
parentscheck$current_age_or_death_age_m = ifelse(!is.na(parentscheck$current_age_or_death_age_m), parentscheck$current_age_or_death_age_m, ifelse(parentscheck$alive_m==1, 2014-parentscheck$birth_year_m, NA))
                                                  parentscheck$current_age_or_death_age_m = ifelse(!is.na(parentscheck$current_age_or_death_age_m), parentscheck$current_age_or_death_age_m, ifelse(parentscheck$alive_m==3, 2014-parentscheck$death_year_m, NA))
                                                  
# Now we aggregate the informations 
parentscheck = parentscheck %>%
  aggregate2sources("age_aggregated", "age", "current_age_or_death_age_m", remove_old_variables = FALSE)

# And we create a variable that contains the age of death for every individual that died:
parentscheck$death_age = ifelse(parentscheck$alive_m == 3, parentscheck$age_aggregated, NA)

# Now we want the birthdates of all individuals that are either still alive or lived longer than 5 years
parentscheck$birth_lived_5y = ifelse(parentscheck$alive_m == 1, parentscheck$birth, ifelse(parentscheck$death_age>5, parentscheck$birth, NA))


### Birthorder calculations
parentscheck = parentscheck %>%
  group_by(mother_pidlink) %>%
  mutate(birthorder_uterus = min_rank(birth_bio), # Biological Birthorder - Uterus
         siblingcount_maternal = sum(kind_of_child_m == 1), # Biological Sibling Count
         birthorder_alive = older_sibs_alive_and_dependent(as.numeric(str_sub(birth, 1, 4)), death_year_m) + 1, # calculates the birthorder of all siblings (bio&adopted) that are alive by the time of the own birth
         # mistake: i would like to calculate the siblingcount_alive - but how?
         birthorder_min5y = min_rank(birth_lived_5y),# calculates the birthorder of all siblings (bio&adopted) that lived longer than 5 years
         siblingcount_min5y = sum(!is.na(birth_lived_5y))) %>% # sibling count for one family for all siblings that lived longer than 5y
  group_by(mother_father_dyad) %>%
    mutate(birthorder_genes = min_rank(birth),
           birthorder_genes = ifelse(is.na(mother_father_dyad), NA, birthorder_genes),
           siblingcount_genes = sum(!is.na(mother_father_dyad))) %>%
  group_by(mother_pidlink, birth) %>%
  mutate(multiple_birth = sum(kind_of_child_m == 1)) %>% # Biological Multiple births (Uterus)
  group_by(mother_pidlink) %>%
  mutate(any_multiple_birth_in_fam = any(multiple_birth > 1)) # Any biological multiple births in one family?

### Graphs
## Biological Birthorder - Uterus
qplot(parentscheck$birthorder_uterus)
ggplot(parentscheck, aes(x=siblingcount_maternal, y=birthorder_uterus)) + geom_jitter()

## Biological Birthorder - Genes
qplot(parentscheck$birthorder_genes)
ggplot(parentscheck, aes(x=siblingcount_genes, y=birthorder_genes)) + geom_jitter()

## Social Birthorder - min 5 years
qplot(parentscheck$birthorder_min5y)
ggplot(parentscheck, aes(x=siblingcount_min5y, y=birthorder_min5y)) + geom_jitter()

## Social Birthorder - alive at birth
qplot(parentscheck$birthorder_alive)

## Bio: Uterus vs. Genes
ggplot(parentscheck, aes(x=birthorder_uterus, y=birthorder_genes)) + geom_jitter()

## Social: min5years vs. alive at birth
ggplot(parentscheck, aes(x=birthorder_min5y, y=birthorder_alive)) + geom_jitter()
```



## Calculate age related t-scores

```{r Calculate age related t-scores}
qplot(data = alldata, factor(age), raven, geom = "blank") + stat_summary( fun.data = "mean_sdl")

### IQ
alldata$raven_t <- 10*ave(alldata$raven, alldata$age, FUN=scale) + 50
qplot(alldata$raven_t)
alldata$math_t <- 10*ave(alldata$math, alldata$age, FUN=scale) + 50
qplot(alldata$math_t)
alldata$count_backwards_t <- 10*ave(alldata$count_backwards, alldata$age, FUN=scale) + 50
qplot(alldata$count_backwards_t)
alldata$words_immediate_t <- 10*ave(alldata$words_immediate, alldata$age, FUN=scale) + 50
qplot(alldata$words_immediate_t)
alldata$words_delayed_t <- 10*ave(alldata$words_delayed, alldata$age, FUN=scale) + 50
qplot(alldata$words_delayed_t)
alldata$adaptive_numbering_t <- 10*ave(alldata$adaptive_numbering, alldata$age, FUN=scale) + 50
qplot(alldata$adaptive_numbering_t)


### Personality
alldata$big5_ext_t <- 10*ave(alldata$big5_ext, alldata$age, FUN=scale) + 50
qplot(alldata$big5_ext_t)
alldata$big5_agree_t <- 10*ave(alldata$big5_agree, alldata$age, FUN=scale) + 50
qplot(alldata$big5_agree_t)
alldata$big5_open_t <- 10*ave(alldata$big5_open, alldata$age, FUN=scale) + 50
qplot(alldata$big5_open_t)
alldata$big5_con_t <- 10*ave(alldata$big5_con, alldata$age, FUN=scale) + 50
qplot(alldata$big5_con_t)
alldata$big5_neu_t <- 10*ave(alldata$big5_neu, alldata$age, FUN=scale) + 50
qplot(alldata$big5_neu_t)


###Risktaking (geht nicht, da es keine intervallskalierte Variable ist (nur 5 level))
```

